//Файл сгенерирован автоматически на основе файла C:/Users/user/workspace/python/CanAst/dbcFiles/Dashboard_PazNG_v0.1.1.dbc, последние изменения Fri Apr 12 17:59:31 2024
#include "canDataBase/canDataBase.h"

using namespace canBus;

canSignalStateStruct gCanSignalState;

const uint8_t ADAS_1_NumberOfSignals = 1;
signalNameCharStruct gSignalName_BlindSpot{"BlindSpot",MAX_LENGTH_NAME};
static CanSignal BlindSpot{ 32, 8, gSignalName_BlindSpot, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ADAS_1_arraySignals[ADAS_1_NumberOfSignals] = {&BlindSpot};
messageNameCharStruct gMessageName_ADAS_1{"ADAS_1",MAX_LENGTH_NAME};
static CanMessageRx ADAS_1(gMessageName_ADAS_1, ADAS_1_arraySignals, ADAS_1_NumberOfSignals, 0x18A9175D, 8, 0);

const uint8_t AIR1_NumberOfSignals = 6;
signalNameCharStruct gSignalName_AirCompressorStatus{"AirCompressorStatus",MAX_LENGTH_NAME};
static CanSignal AirCompressorStatus{ 48, 2, gSignalName_AirCompressorStatus, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_AirSuspensionSupplyPressure{"AirSuspensionSupplyPressure",MAX_LENGTH_NAME};
static CanSignal AirSuspensionSupplyPressure{ 40, 8, gSignalName_AirSuspensionSupplyPressure, 8, 0, canIntel, canUint, 2000, 0, 0};
signalNameCharStruct gSignalName_AuxiliaryEquipmentSupplyPressure{"AuxiliaryEquipmentSupplyPressure",MAX_LENGTH_NAME};
static CanSignal AuxiliaryEquipmentSupplyPressure{ 32, 8, gSignalName_AuxiliaryEquipmentSupplyPressure, 8, 0, canIntel, canUint, 2000, 0, 0};
signalNameCharStruct gSignalName_ParkingAirPressure{"ParkingAirPressure",MAX_LENGTH_NAME};
static CanSignal ParkingAirPressure{ 8, 8, gSignalName_ParkingAirPressure, 8, 0, canIntel, canUint, 2000, 0, 0};
signalNameCharStruct gSignalName_ServiceBrakeCircuit1AirPress{"ServiceBrakeCircuit1AirPress",MAX_LENGTH_NAME};
static CanSignal ServiceBrakeCircuit1AirPress{ 16, 8, gSignalName_ServiceBrakeCircuit1AirPress, 8, 0, canIntel, canUint, 2000, 0, 0};
signalNameCharStruct gSignalName_ServiceBrakeCircuit2AirPress{"ServiceBrakeCircuit2AirPress",MAX_LENGTH_NAME};
static CanSignal ServiceBrakeCircuit2AirPress{ 24, 8, gSignalName_ServiceBrakeCircuit2AirPress, 8, 0, canIntel, canUint, 2000, 0, 0};
static CanSignal *AIR1_arraySignals[AIR1_NumberOfSignals] = {&AirCompressorStatus, &AirSuspensionSupplyPressure, &AuxiliaryEquipmentSupplyPressure, &ParkingAirPressure, &ServiceBrakeCircuit1AirPress, &ServiceBrakeCircuit2AirPress};
messageNameCharStruct gMessageName_AIR1{"AIR1",MAX_LENGTH_NAME};
static CanMessageRx AIR1(gMessageName_AIR1, AIR1_arraySignals, AIR1_NumberOfSignals, 0x18FEAE30, 8, 100);

const uint8_t AMB_NumberOfSignals = 3;
signalNameCharStruct gSignalName_AmbientAirTemp{"AmbientAirTemp",MAX_LENGTH_NAME};
static CanSignal AmbientAirTemp{ 24, 16, gSignalName_AmbientAirTemp, 0.03125, -273, canIntel, canUint, 1734.96875, -273, 0};
signalNameCharStruct gSignalName_CabInteriorTempA{"CabInteriorTempA",MAX_LENGTH_NAME};
static CanSignal CabInteriorTempA{ 8, 16, gSignalName_CabInteriorTempA, 0.03125, -273, canIntel, canUint, 1734.97, -273, 0};
signalNameCharStruct gSignalName_CabInteriorTempB{"CabInteriorTempB",MAX_LENGTH_NAME};
static CanSignal CabInteriorTempB{ 40, 16, gSignalName_CabInteriorTempB, 0.03125, -273, canIntel, canUint, 1734.97, -273, 0};
static CanSignal *AMB_arraySignals[AMB_NumberOfSignals] = {&AmbientAirTemp, &CabInteriorTempA, &CabInteriorTempB};
messageNameCharStruct gMessageName_AMB{"AMB",MAX_LENGTH_NAME};
static CanMessageRx AMB(gMessageName_AMB, AMB_arraySignals, AMB_NumberOfSignals, 0x18FEF51E, 8, 1000);

const uint8_t ASC1_NumberOfSignals = 11;
signalNameCharStruct gSignalName_AboveNominalLevelFrontAxle{"AboveNominalLevelFrontAxle",MAX_LENGTH_NAME};
static CanSignal AboveNominalLevelFrontAxle{ 12, 2, gSignalName_AboveNominalLevelFrontAxle, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_AboveNominalLevelRearAxle{"AboveNominalLevelRearAxle",MAX_LENGTH_NAME};
static CanSignal AboveNominalLevelRearAxle{ 14, 2, gSignalName_AboveNominalLevelRearAxle, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_BelowNominalLevelFrontAxle{"BelowNominalLevelFrontAxle",MAX_LENGTH_NAME};
static CanSignal BelowNominalLevelFrontAxle{ 8, 2, gSignalName_BelowNominalLevelFrontAxle, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_BelowNominalLevelRearAxle{"BelowNominalLevelRearAxle",MAX_LENGTH_NAME};
static CanSignal BelowNominalLevelRearAxle{ 10, 2, gSignalName_BelowNominalLevelRearAxle, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_KneelingInformation{"KneelingInformation",MAX_LENGTH_NAME};
static CanSignal KneelingInformation{ 24, 4, gSignalName_KneelingInformation, 1, 0, canIntel, canUint, 15, 0, 0};
signalNameCharStruct gSignalName_LiftingControlModeFrontAxle{"LiftingControlModeFrontAxle",MAX_LENGTH_NAME};
static CanSignal LiftingControlModeFrontAxle{ 20, 2, gSignalName_LiftingControlModeFrontAxle, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_LiftingControlModeRearAxle{"LiftingControlModeRearAxle",MAX_LENGTH_NAME};
static CanSignal LiftingControlModeRearAxle{ 22, 2, gSignalName_LiftingControlModeRearAxle, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_LoweringControlModeFrontAxle{"LoweringControlModeFrontAxle",MAX_LENGTH_NAME};
static CanSignal LoweringControlModeFrontAxle{ 16, 2, gSignalName_LoweringControlModeFrontAxle, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_LoweringControlModeRearAxle{"LoweringControlModeRearAxle",MAX_LENGTH_NAME};
static CanSignal LoweringControlModeRearAxle{ 18, 2, gSignalName_LoweringControlModeRearAxle, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_NominalLevelFrontAxle{"NominalLevelFrontAxle",MAX_LENGTH_NAME};
static CanSignal NominalLevelFrontAxle{ 0, 4, gSignalName_NominalLevelFrontAxle, 1, 0, canIntel, canUint, 15, 0, 0};
signalNameCharStruct gSignalName_NominalLevelRearAxle{"NominalLevelRearAxle",MAX_LENGTH_NAME};
static CanSignal NominalLevelRearAxle{ 4, 4, gSignalName_NominalLevelRearAxle, 1, 0, canIntel, canUint, 15, 0, 0};
static CanSignal *ASC1_arraySignals[ASC1_NumberOfSignals] = {&AboveNominalLevelFrontAxle, &AboveNominalLevelRearAxle, &BelowNominalLevelFrontAxle, &BelowNominalLevelRearAxle, &KneelingInformation, &LiftingControlModeFrontAxle, &LiftingControlModeRearAxle, &LoweringControlModeFrontAxle, &LoweringControlModeRearAxle, &NominalLevelFrontAxle, &NominalLevelRearAxle};
messageNameCharStruct gMessageName_ASC1{"ASC1",MAX_LENGTH_NAME};
static CanMessageRx ASC1(gMessageName_ASC1, ASC1_arraySignals, ASC1_NumberOfSignals, 0x0CFE5A2F, 8, 100);

const uint8_t ASC2_NumberOfSignals = 1;
signalNameCharStruct gSignalName_AutoKneeling{"AutoKneeling",MAX_LENGTH_NAME};
static CanSignal AutoKneeling{ 6, 2, gSignalName_AutoKneeling, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ASC2_arraySignals[ASC2_NumberOfSignals] = {&AutoKneeling};
messageNameCharStruct gMessageName_ASC2{"ASC2",MAX_LENGTH_NAME};
static CanMessageRx ASC2(gMessageName_ASC2, ASC2_arraySignals, ASC2_NumberOfSignals, 0x0CD22F27, 8, 100);

const uint8_t BDS_NumberOfSignals = 1;
signalNameCharStruct gSignalName_SeatBeltSwitch{"SeatBeltSwitch",MAX_LENGTH_NAME};
static CanSignal SeatBeltSwitch{ 0, 2, gSignalName_SeatBeltSwitch, 1, 0, canIntel, canUint, 3, 0, 0};
static CanSignal *BDS_arraySignals[BDS_NumberOfSignals] = {&SeatBeltSwitch};
messageNameCharStruct gMessageName_BDS{"BDS",MAX_LENGTH_NAME};
static CanMessageRx BDS(gMessageName_BDS, BDS_arraySignals, BDS_NumberOfSignals, 0x14FD171E, 8, 50);

const uint8_t CCUT1_NumberOfSignals = 4;
signalNameCharStruct gSignalName_RoofTemp{"RoofTemp",MAX_LENGTH_NAME};
static CanSignal RoofTemp{ 48, 8, gSignalName_RoofTemp, 1, -40, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_SalonTemp_1{"SalonTemp_1",MAX_LENGTH_NAME};
static CanSignal SalonTemp_1{ 0, 8, gSignalName_SalonTemp_1, 1, -40, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_SalonTemp_2{"SalonTemp_2",MAX_LENGTH_NAME};
static CanSignal SalonTemp_2{ 8, 8, gSignalName_SalonTemp_2, 1, -40, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_SalonTemp_3{"SalonTemp_3",MAX_LENGTH_NAME};
static CanSignal SalonTemp_3{ 16, 8, gSignalName_SalonTemp_3, 1, -40, canIntel, canUint, 0, 0, 0};
static CanSignal *CCUT1_arraySignals[CCUT1_NumberOfSignals] = {&RoofTemp, &SalonTemp_1, &SalonTemp_2, &SalonTemp_3};
messageNameCharStruct gMessageName_CCUT1{"CCUT1",MAX_LENGTH_NAME};
static CanMessageRx CCUT1(gMessageName_CCUT1, CCUT1_arraySignals, CCUT1_NumberOfSignals, 0x18FF0D3A, 8, 500);

const uint8_t CCVS1_NumberOfSignals = 3;
signalNameCharStruct gSignalName_CruiseControlActive{"CruiseControlActive",MAX_LENGTH_NAME};
static CanSignal CruiseControlActive{ 24, 2, gSignalName_CruiseControlActive, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_ParkingBrakeState{"ParkingBrakeState",MAX_LENGTH_NAME};
static CanSignal ParkingBrakeState{ 2, 2, gSignalName_ParkingBrakeState, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_WheelBasedVehicleSpeed{"WheelBasedVehicleSpeed",MAX_LENGTH_NAME};
static CanSignal WheelBasedVehicleSpeed{ 8, 16, gSignalName_WheelBasedVehicleSpeed, 0.00390625, 0, canIntel, canUint, 250.996, 0, 0};
static CanSignal *CCVS1_arraySignals[CCVS1_NumberOfSignals] = {&CruiseControlActive, &ParkingBrakeState, &WheelBasedVehicleSpeed};
messageNameCharStruct gMessageName_CCVS1{"CCVS1",MAX_LENGTH_NAME};
static CanMessageRx CCVS1(gMessageName_CCVS1, CCVS1_arraySignals, CCVS1_NumberOfSignals, 0x18FEF100, 8, 100);

const uint8_t CCVS1_03_NumberOfSignals = 1;
signalNameCharStruct gSignalName_VehicleSpeed_03{"VehicleSpeed_03",MAX_LENGTH_NAME};
static CanSignal VehicleSpeed_03{ 8, 16, gSignalName_VehicleSpeed_03, 0.00390625, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CCVS1_03_arraySignals[CCVS1_03_NumberOfSignals] = {&VehicleSpeed_03};
messageNameCharStruct gMessageName_CCVS1_03{"CCVS1_03",MAX_LENGTH_NAME};
static CanMessageRx CCVS1_03(gMessageName_CCVS1_03, CCVS1_03_arraySignals, CCVS1_03_NumberOfSignals, 0x18FEF103, 8, 100);

const uint8_t CDC_NumberOfSignals = 2;
signalNameCharStruct gSignalName_MirrorHeatLeft{"MirrorHeatLeft",MAX_LENGTH_NAME};
static CanSignal MirrorHeatLeft{ 48, 2, gSignalName_MirrorHeatLeft, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_MirrorHeatRight{"MirrorHeatRight",MAX_LENGTH_NAME};
static CanSignal MirrorHeatRight{ 50, 2, gSignalName_MirrorHeatRight, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CDC_arraySignals[CDC_NumberOfSignals] = {&MirrorHeatLeft, &MirrorHeatRight};
messageNameCharStruct gMessageName_CDC{"CDC",MAX_LENGTH_NAME};
static CanMessageRx CDC(gMessageName_CDC, CDC_arraySignals, CDC_NumberOfSignals, 0x14FC121E, 8, 100);

const uint8_t CECU_06_NumberOfSignals = 2;
signalNameCharStruct gSignalName_ChargeConnect{"ChargeConnect",MAX_LENGTH_NAME};
static CanSignal ChargeConnect{ 8, 2, gSignalName_ChargeConnect, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_LimitedPower{"LimitedPower",MAX_LENGTH_NAME};
static CanSignal LimitedPower{ 12, 2, gSignalName_LimitedPower, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CECU_06_arraySignals[CECU_06_NumberOfSignals] = {&ChargeConnect, &LimitedPower};
messageNameCharStruct gMessageName_CECU_06{"CECU_06",MAX_LENGTH_NAME};
static CanMessageRx CECU_06(gMessageName_CECU_06, CECU_06_arraySignals, CECU_06_NumberOfSignals, 0x18FD065B, 8, 1000);

const uint8_t CECU_A0_NumberOfSignals = 7;
signalNameCharStruct gSignalName_EstimatedRange{"EstimatedRange",MAX_LENGTH_NAME};
static CanSignal EstimatedRange{ 16, 8, gSignalName_EstimatedRange, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_PantConnect{"PantConnect",MAX_LENGTH_NAME};
static CanSignal PantConnect{ 14, 1, gSignalName_PantConnect, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_PantError{"PantError",MAX_LENGTH_NAME};
static CanSignal PantError{ 15, 1, gSignalName_PantError, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_PantMove{"PantMove",MAX_LENGTH_NAME};
static CanSignal PantMove{ 12, 1, gSignalName_PantMove, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_PantUp{"PantUp",MAX_LENGTH_NAME};
static CanSignal PantUp{ 13, 1, gSignalName_PantUp, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_PowerSteeringError{"PowerSteeringError",MAX_LENGTH_NAME};
static CanSignal PowerSteeringError{ 3, 1, gSignalName_PowerSteeringError, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_PowerSteeringOverheat{"PowerSteeringOverheat",MAX_LENGTH_NAME};
static CanSignal PowerSteeringOverheat{ 6, 1, gSignalName_PowerSteeringOverheat, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CECU_A0_arraySignals[CECU_A0_NumberOfSignals] = {&EstimatedRange, &PantConnect, &PantError, &PantMove, &PantUp, &PowerSteeringError, &PowerSteeringOverheat};
messageNameCharStruct gMessageName_CECU_A0{"CECU_A0",MAX_LENGTH_NAME};
static CanMessageRx CECU_A0(gMessageName_CECU_A0, CECU_A0_arraySignals, CECU_A0_NumberOfSignals, 0x1830A05B, 8, 1000);

const uint8_t CECU_A1_NumberOfSignals = 5;
signalNameCharStruct gSignalName_AirCompressorError{"AirCompressorError",MAX_LENGTH_NAME};
static CanSignal AirCompressorError{ 16, 3, gSignalName_AirCompressorError, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_ContactorError{"ContactorError",MAX_LENGTH_NAME};
static CanSignal ContactorError{ 0, 8, gSignalName_ContactorError, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_IsoControlError{"IsoControlError",MAX_LENGTH_NAME};
static CanSignal IsoControlError{ 12, 2, gSignalName_IsoControlError, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_IsoControlGreen{"IsoControlGreen",MAX_LENGTH_NAME};
static CanSignal IsoControlGreen{ 8, 2, gSignalName_IsoControlGreen, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_IsoControlWarning{"IsoControlWarning",MAX_LENGTH_NAME};
static CanSignal IsoControlWarning{ 10, 2, gSignalName_IsoControlWarning, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CECU_A1_arraySignals[CECU_A1_NumberOfSignals] = {&AirCompressorError, &ContactorError, &IsoControlError, &IsoControlGreen, &IsoControlWarning};
messageNameCharStruct gMessageName_CECU_A1{"CECU_A1",MAX_LENGTH_NAME};
static CanMessageRx CECU_A1(gMessageName_CECU_A1, CECU_A1_arraySignals, CECU_A1_NumberOfSignals, 0x1830A15B, 8, 1000);

const uint8_t CL_NumberOfSignals = 1;
signalNameCharStruct gSignalName_SalonLightning{"SalonLightning",MAX_LENGTH_NAME};
static CanSignal SalonLightning{ 8, 8, gSignalName_SalonLightning, 0.4, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CL_arraySignals[CL_NumberOfSignals] = {&SalonLightning};
messageNameCharStruct gMessageName_CL{"CL",MAX_LENGTH_NAME};
static CanMessageRx CL(gMessageName_CL, CL_arraySignals, CL_NumberOfSignals, 0x18D0171E, 8, 100);

const uint8_t CM1_NumberOfSignals = 4;
signalNameCharStruct gSignalName_AuxHeaterCoolantPumpReq{"AuxHeaterCoolantPumpReq",MAX_LENGTH_NAME};
static CanSignal AuxHeaterCoolantPumpReq{ 24, 2, gSignalName_AuxHeaterCoolantPumpReq, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_AuxHeaterModeReq{"AuxHeaterModeReq",MAX_LENGTH_NAME};
static CanSignal AuxHeaterModeReq{ 48, 4, gSignalName_AuxHeaterModeReq, 1, 0, canIntel, canUint, 15, 0, 0};
signalNameCharStruct gSignalName_OperatorSeatDirectionSwitch{"OperatorSeatDirectionSwitch",MAX_LENGTH_NAME};
static CanSignal OperatorSeatDirectionSwitch{ 28, 2, gSignalName_OperatorSeatDirectionSwitch, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_RequestedPercentFanSpeed{"RequestedPercentFanSpeed",MAX_LENGTH_NAME};
static CanSignal RequestedPercentFanSpeed{ 0, 8, gSignalName_RequestedPercentFanSpeed, 0.4, 0, canIntel, canUint, 100, 0, 0};
static CanSignal *CM1_arraySignals[CM1_NumberOfSignals] = {&AuxHeaterCoolantPumpReq, &AuxHeaterModeReq, &OperatorSeatDirectionSwitch, &RequestedPercentFanSpeed};
messageNameCharStruct gMessageName_CM1{"CM1",MAX_LENGTH_NAME};
static CanMessageRx CM1(gMessageName_CM1, CM1_arraySignals, CM1_NumberOfSignals, 0x18FE171E, 8, 1000);

const uint8_t CM1_E1_NumberOfSignals = 1;
signalNameCharStruct gSignalName_HeaterLiquidState{"HeaterLiquidState",MAX_LENGTH_NAME};
static CanSignal HeaterLiquidState{ 48, 4, gSignalName_HeaterLiquidState, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CM1_E1_arraySignals[CM1_E1_NumberOfSignals] = {&HeaterLiquidState};
messageNameCharStruct gMessageName_CM1_E1{"CM1_E1",MAX_LENGTH_NAME};
static CanMessageRx CM1_E1(gMessageName_CM1_E1, CM1_E1_arraySignals, CM1_E1_NumberOfSignals, 0x18FE17E1, 8, 0);

const uint8_t DC1_NumberOfSignals = 1;
signalNameCharStruct gSignalName_RampError{"RampError",MAX_LENGTH_NAME};
static CanSignal RampError{ 4, 2, gSignalName_RampError, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DC1_arraySignals[DC1_NumberOfSignals] = {&RampError};
messageNameCharStruct gMessageName_DC1{"DC1",MAX_LENGTH_NAME};
static CanMessageRx DC1(gMessageName_DC1, DC1_arraySignals, DC1_NumberOfSignals, 0x18FE4E1E, 8, 100);

const uint8_t DC2_NumberOfSignals = 1;
signalNameCharStruct gSignalName_EngineHatchOpen{"EngineHatchOpen",MAX_LENGTH_NAME};
static CanSignal EngineHatchOpen{ 50, 2, gSignalName_EngineHatchOpen, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DC2_arraySignals[DC2_NumberOfSignals] = {&EngineHatchOpen};
messageNameCharStruct gMessageName_DC2{"DC2",MAX_LENGTH_NAME};
static CanMessageRx DC2(gMessageName_DC2, DC2_arraySignals, DC2_NumberOfSignals, 0x18FDA51E, 8, 100);

const uint8_t DCU1_NumberOfSignals = 4;
signalNameCharStruct gSignalName_Door1EmergencyOpening1{"Door1EmergencyOpening1",MAX_LENGTH_NAME};
static CanSignal Door1EmergencyOpening1{ 10, 2, gSignalName_Door1EmergencyOpening1, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_Door1NotDefine{"Door1NotDefine",MAX_LENGTH_NAME};
static CanSignal Door1NotDefine{ 16, 2, gSignalName_Door1NotDefine, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_Door1Open{"Door1Open",MAX_LENGTH_NAME};
static CanSignal Door1Open{ 0, 4, gSignalName_Door1Open, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_Door1Pinching{"Door1Pinching",MAX_LENGTH_NAME};
static CanSignal Door1Pinching{ 12, 2, gSignalName_Door1Pinching, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DCU1_arraySignals[DCU1_NumberOfSignals] = {&Door1EmergencyOpening1, &Door1NotDefine, &Door1Open, &Door1Pinching};
messageNameCharStruct gMessageName_DCU1{"DCU1",MAX_LENGTH_NAME};
static CanMessageRx DCU1(gMessageName_DCU1, DCU1_arraySignals, DCU1_NumberOfSignals, 0x18FFBCEC, 8, 100);

const uint8_t DCU2_NumberOfSignals = 4;
signalNameCharStruct gSignalName_Door2EmergencyOpening1{"Door2EmergencyOpening1",MAX_LENGTH_NAME};
static CanSignal Door2EmergencyOpening1{ 10, 2, gSignalName_Door2EmergencyOpening1, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_Door2NotDefine{"Door2NotDefine",MAX_LENGTH_NAME};
static CanSignal Door2NotDefine{ 16, 2, gSignalName_Door2NotDefine, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_Door2Open{"Door2Open",MAX_LENGTH_NAME};
static CanSignal Door2Open{ 0, 4, gSignalName_Door2Open, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_Door2Pinching{"Door2Pinching",MAX_LENGTH_NAME};
static CanSignal Door2Pinching{ 12, 2, gSignalName_Door2Pinching, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DCU2_arraySignals[DCU2_NumberOfSignals] = {&Door2EmergencyOpening1, &Door2NotDefine, &Door2Open, &Door2Pinching};
messageNameCharStruct gMessageName_DCU2{"DCU2",MAX_LENGTH_NAME};
static CanMessageRx DCU2(gMessageName_DCU2, DCU2_arraySignals, DCU2_NumberOfSignals, 0x18FFBCED, 8, 100);

const uint8_t DCU3_NumberOfSignals = 4;
signalNameCharStruct gSignalName_Door3EmergencyOpening1{"Door3EmergencyOpening1",MAX_LENGTH_NAME};
static CanSignal Door3EmergencyOpening1{ 10, 2, gSignalName_Door3EmergencyOpening1, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_Door3NotDefine{"Door3NotDefine",MAX_LENGTH_NAME};
static CanSignal Door3NotDefine{ 16, 2, gSignalName_Door3NotDefine, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_Door3Open{"Door3Open",MAX_LENGTH_NAME};
static CanSignal Door3Open{ 0, 4, gSignalName_Door3Open, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_Door3Pinching{"Door3Pinching",MAX_LENGTH_NAME};
static CanSignal Door3Pinching{ 12, 2, gSignalName_Door3Pinching, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DCU3_arraySignals[DCU3_NumberOfSignals] = {&Door3EmergencyOpening1, &Door3NotDefine, &Door3Open, &Door3Pinching};
messageNameCharStruct gMessageName_DCU3{"DCU3",MAX_LENGTH_NAME};
static CanMessageRx DCU3(gMessageName_DCU3, DCU3_arraySignals, DCU3_NumberOfSignals, 0x18FFBCE9, 8, 100);

const uint8_t DD1_12_NumberOfSignals = 1;
signalNameCharStruct gSignalName_DD1_ReserveFuelLevel{"DD1_ReserveFuelLevel",MAX_LENGTH_NAME};
static CanSignal DD1_ReserveFuelLevel{ 8, 8, gSignalName_DD1_ReserveFuelLevel, 0.4, 0, canIntel, canUint, 100, 0, 0};
static CanSignal *DD1_12_arraySignals[DD1_12_NumberOfSignals] = {&DD1_ReserveFuelLevel};
messageNameCharStruct gMessageName_DD1_12{"DD1_12",MAX_LENGTH_NAME};
static CanMessageRx DD1_12(gMessageName_DD1_12, DD1_12_arraySignals, DD1_12_NumberOfSignals, 0x18FEFC12, 8, 1000);

const uint8_t DD1_1E_NumberOfSignals = 2;
signalNameCharStruct gSignalName_CargoAmbientTemp{"CargoAmbientTemp",MAX_LENGTH_NAME};
static CanSignal CargoAmbientTemp{ 32, 16, gSignalName_CargoAmbientTemp, 1, -273, canIntel, canUint, 1734.96875, -273, 0};
signalNameCharStruct gSignalName_DD1_WasherFluidLow{"DD1_WasherFluidLow",MAX_LENGTH_NAME};
static CanSignal DD1_WasherFluidLow{ 0, 8, gSignalName_DD1_WasherFluidLow, 0.4, 0, canIntel, canUint, 100, 0, 0};
static CanSignal *DD1_1E_arraySignals[DD1_1E_NumberOfSignals] = {&CargoAmbientTemp, &DD1_WasherFluidLow};
messageNameCharStruct gMessageName_DD1_1E{"DD1_1E",MAX_LENGTH_NAME};
static CanMessageRx DD1_1E(gMessageName_DD1_1E, DD1_1E_arraySignals, DD1_1E_NumberOfSignals, 0x18FEFC1E, 8, 1000);

const uint8_t DLDC1_NumberOfSignals = 1;
signalNameCharStruct gSignalName_LowLevel_CL{"LowLevel_CL",MAX_LENGTH_NAME};
static CanSignal LowLevel_CL{ 16, 2, gSignalName_LowLevel_CL, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DLDC1_arraySignals[DLDC1_NumberOfSignals] = {&LowLevel_CL};
messageNameCharStruct gMessageName_DLDC1{"DLDC1",MAX_LENGTH_NAME};
static CanMessageRx DLDC1(gMessageName_DLDC1, DLDC1_arraySignals, DLDC1_NumberOfSignals, 0x18FD055B, 8, 100);

const uint8_t DM1_EBS_NumberOfSignals = 2;
signalNameCharStruct gSignalName_EbsError{"EbsError",MAX_LENGTH_NAME};
static CanSignal EbsError{ 4, 2, gSignalName_EbsError, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_EbsWarning{"EbsWarning",MAX_LENGTH_NAME};
static CanSignal EbsWarning{ 2, 2, gSignalName_EbsWarning, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DM1_EBS_arraySignals[DM1_EBS_NumberOfSignals] = {&EbsError, &EbsWarning};
messageNameCharStruct gMessageName_DM1_EBS{"DM1_EBS",MAX_LENGTH_NAME};
static CanMessageRx DM1_EBS(gMessageName_DM1_EBS, DM1_EBS_arraySignals, DM1_EBS_NumberOfSignals, 0x18FECA0B, 8, 1000);

const uint8_t DM1_EPB_NumberOfSignals = 1;
signalNameCharStruct gSignalName_EPB_Error{"EPB_Error",MAX_LENGTH_NAME};
static CanSignal EPB_Error{ 4, 2, gSignalName_EPB_Error, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DM1_EPB_arraySignals[DM1_EPB_NumberOfSignals] = {&EPB_Error};
messageNameCharStruct gMessageName_DM1_EPB{"DM1_EPB",MAX_LENGTH_NAME};
static CanMessageRx DM1_EPB(gMessageName_DM1_EPB, DM1_EPB_arraySignals, DM1_EPB_NumberOfSignals, 0x18FECA50, 8, 1000);

const uint8_t EBC1_NumberOfSignals = 9;
signalNameCharStruct gSignalName_ABS_Active{"ABS_Active",MAX_LENGTH_NAME};
static CanSignal ABS_Active{ 4, 2, gSignalName_ABS_Active, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_ABS_FullyOpeartinal{"ABS_FullyOpeartinal",MAX_LENGTH_NAME};
static CanSignal ABS_FullyOpeartinal{ 40, 2, gSignalName_ABS_FullyOpeartinal, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_ASR_BrakeControlActive{"ASR_BrakeControlActive",MAX_LENGTH_NAME};
static CanSignal ASR_BrakeControlActive{ 2, 2, gSignalName_ASR_BrakeControlActive, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_ASR_EngineControlActive{"ASR_EngineControlActive",MAX_LENGTH_NAME};
static CanSignal ASR_EngineControlActive{ 0, 2, gSignalName_ASR_EngineControlActive, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_ASR_HillHolderSwitch{"ASR_HillHolderSwitch",MAX_LENGTH_NAME};
static CanSignal ASR_HillHolderSwitch{ 20, 2, gSignalName_ASR_HillHolderSwitch, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_ASR_OffRoadSwitch{"ASR_OffRoadSwitch",MAX_LENGTH_NAME};
static CanSignal ASR_OffRoadSwitch{ 18, 2, gSignalName_ASR_OffRoadSwitch, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_ASR_infoSignal{"ASR_infoSignal",MAX_LENGTH_NAME};
static CanSignal ASR_infoSignal{ 46, 2, gSignalName_ASR_infoSignal, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_EBS_RedLamp{"EBS_RedLamp",MAX_LENGTH_NAME};
static CanSignal EBS_RedLamp{ 42, 2, gSignalName_EBS_RedLamp, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_EBS_WarningLamp{"EBS_WarningLamp",MAX_LENGTH_NAME};
static CanSignal EBS_WarningLamp{ 44, 2, gSignalName_EBS_WarningLamp, 1, 0, canIntel, canUint, 3, 0, 0};
static CanSignal *EBC1_arraySignals[EBC1_NumberOfSignals] = {&ABS_Active, &ABS_FullyOpeartinal, &ASR_BrakeControlActive, &ASR_EngineControlActive, &ASR_HillHolderSwitch, &ASR_OffRoadSwitch, &ASR_infoSignal, &EBS_RedLamp, &EBS_WarningLamp};
messageNameCharStruct gMessageName_EBC1{"EBC1",MAX_LENGTH_NAME};
static CanMessageRx EBC1(gMessageName_EBC1, EBC1_arraySignals, EBC1_NumberOfSignals, 0x18F0010B, 8, 100);

const uint8_t EBC4_NumberOfSignals = 8;
signalNameCharStruct gSignalName_FrontAxleLeft{"FrontAxleLeft",MAX_LENGTH_NAME};
static CanSignal FrontAxleLeft{ 0, 8, gSignalName_FrontAxleLeft, 0.4, 0, canIntel, canUint, 100, 0, 0};
signalNameCharStruct gSignalName_FrontAxleRight{"FrontAxleRight",MAX_LENGTH_NAME};
static CanSignal FrontAxleRight{ 8, 8, gSignalName_FrontAxleRight, 0.4, 0, canIntel, canUint, 100, 0, 0};
signalNameCharStruct gSignalName_RearAxle1LeftWheel{"RearAxle1LeftWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle1LeftWheel{ 16, 8, gSignalName_RearAxle1LeftWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
signalNameCharStruct gSignalName_RearAxle1RightWheel{"RearAxle1RightWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle1RightWheel{ 24, 8, gSignalName_RearAxle1RightWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
signalNameCharStruct gSignalName_RearAxle2LeftWheel{"RearAxle2LeftWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle2LeftWheel{ 32, 8, gSignalName_RearAxle2LeftWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
signalNameCharStruct gSignalName_RearAxle2RightWheel{"RearAxle2RightWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle2RightWheel{ 40, 8, gSignalName_RearAxle2RightWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
signalNameCharStruct gSignalName_RearAxle3LeftWheel{"RearAxle3LeftWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle3LeftWheel{ 48, 8, gSignalName_RearAxle3LeftWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
signalNameCharStruct gSignalName_RearAxle3RightWheel{"RearAxle3RightWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle3RightWheel{ 56, 8, gSignalName_RearAxle3RightWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
static CanSignal *EBC4_arraySignals[EBC4_NumberOfSignals] = {&FrontAxleLeft, &FrontAxleRight, &RearAxle1LeftWheel, &RearAxle1RightWheel, &RearAxle2LeftWheel, &RearAxle2RightWheel, &RearAxle3LeftWheel, &RearAxle3RightWheel};
messageNameCharStruct gMessageName_EBC4{"EBC4",MAX_LENGTH_NAME};
static CanMessageRx EBC4(gMessageName_EBC4, EBC4_arraySignals, EBC4_NumberOfSignals, 0x1CFEAC0B, 8, 100);

const uint8_t EBC5_NumberOfSignals = 2;
signalNameCharStruct gSignalName_HaltBrakeMode{"HaltBrakeMode",MAX_LENGTH_NAME};
static CanSignal HaltBrakeMode{ 2, 3, gSignalName_HaltBrakeMode, 1, 0, canIntel, canUint, 7, 0, 0};
signalNameCharStruct gSignalName_HillHolderMode{"HillHolderMode",MAX_LENGTH_NAME};
static CanSignal HillHolderMode{ 5, 3, gSignalName_HillHolderMode, 1, 0, canIntel, canUint, 7, 0, 0};
static CanSignal *EBC5_arraySignals[EBC5_NumberOfSignals] = {&HaltBrakeMode, &HillHolderMode};
messageNameCharStruct gMessageName_EBC5{"EBC5",MAX_LENGTH_NAME};
static CanMessageRx EBC5(gMessageName_EBC5, EBC5_arraySignals, EBC5_NumberOfSignals, 0x18FDC40B, 8, 100);

const uint8_t ECO_NumberOfSignals = 1;
signalNameCharStruct gSignalName_Eco_s{"Eco_s",MAX_LENGTH_NAME};
static CanSignal Eco_s{ 52, 2, gSignalName_Eco_s, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ECO_arraySignals[ECO_NumberOfSignals] = {&Eco_s};
messageNameCharStruct gMessageName_ECO{"ECO",MAX_LENGTH_NAME};
static CanMessageRx ECO(gMessageName_ECO, ECO_arraySignals, ECO_NumberOfSignals, 0x18FF083A, 8, 100);

const uint8_t EDSC2_2_NumberOfSignals = 2;
signalNameCharStruct gSignalName_RequestOpenRamp1{"RequestOpenRamp1",MAX_LENGTH_NAME};
static CanSignal RequestOpenRamp1{ 4, 2, gSignalName_RequestOpenRamp1, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_RequestOpenRamp2{"RequestOpenRamp2",MAX_LENGTH_NAME};
static CanSignal RequestOpenRamp2{ 6, 2, gSignalName_RequestOpenRamp2, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *EDSC2_2_arraySignals[EDSC2_2_NumberOfSignals] = {&RequestOpenRamp1, &RequestOpenRamp2};
messageNameCharStruct gMessageName_EDSC2_2{"EDSC2_2",MAX_LENGTH_NAME};
static CanMessageRx EDSC2_2(gMessageName_EDSC2_2, EDSC2_2_arraySignals, EDSC2_2_NumberOfSignals, 0x18FFBDCD, 8, 100);

const uint8_t ELECTRO_1_NumberOfSignals = 4;
signalNameCharStruct gSignalName_HvBatteryOn{"HvBatteryOn",MAX_LENGTH_NAME};
static CanSignal HvBatteryOn{ 56, 2, gSignalName_HvBatteryOn, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_HvCurrent{"HvCurrent",MAX_LENGTH_NAME};
static CanSignal HvCurrent{ 48, 8, gSignalName_HvCurrent, 4, -500, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_HvSoc{"HvSoc",MAX_LENGTH_NAME};
static CanSignal HvSoc{ 32, 8, gSignalName_HvSoc, 0.4, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_HvVoltage{"HvVoltage",MAX_LENGTH_NAME};
static CanSignal HvVoltage{ 40, 8, gSignalName_HvVoltage, 3.2, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ELECTRO_1_arraySignals[ELECTRO_1_NumberOfSignals] = {&HvBatteryOn, &HvCurrent, &HvSoc, &HvVoltage};
messageNameCharStruct gMessageName_ELECTRO_1{"ELECTRO_1",MAX_LENGTH_NAME};
static CanMessageRx ELECTRO_1(gMessageName_ELECTRO_1, ELECTRO_1_arraySignals, ELECTRO_1_NumberOfSignals, 0x18FF9F5B, 8, 50);

const uint8_t EPBS1_NumberOfSignals = 2;
signalNameCharStruct gSignalName_AutoHold{"AutoHold",MAX_LENGTH_NAME};
static CanSignal AutoHold{ 4, 2, gSignalName_AutoHold, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_ParkingBrake{"ParkingBrake",MAX_LENGTH_NAME};
static CanSignal ParkingBrake{ 0, 2, gSignalName_ParkingBrake, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *EPBS1_arraySignals[EPBS1_NumberOfSignals] = {&AutoHold, &ParkingBrake};
messageNameCharStruct gMessageName_EPBS1{"EPBS1",MAX_LENGTH_NAME};
static CanMessageRx EPBS1(gMessageName_EPBS1, EPBS1_arraySignals, EPBS1_NumberOfSignals, 0x18FE1250, 8, 100);

const uint8_t ET1_NumberOfSignals = 1;
signalNameCharStruct gSignalName_Temp_CL{"Temp_CL",MAX_LENGTH_NAME};
static CanSignal Temp_CL{ 0, 8, gSignalName_Temp_CL, 1, -40, canIntel, canUint, 0, 0, 0};
static CanSignal *ET1_arraySignals[ET1_NumberOfSignals] = {&Temp_CL};
messageNameCharStruct gMessageName_ET1{"ET1",MAX_LENGTH_NAME};
static CanMessageRx ET1(gMessageName_ET1, ET1_arraySignals, ET1_NumberOfSignals, 0x18FEEE5B, 8, 0);

const uint8_t ETC2_NumberOfSignals = 1;
signalNameCharStruct gSignalName_TransmissionCurrentGear{"TransmissionCurrentGear",MAX_LENGTH_NAME};
static CanSignal TransmissionCurrentGear{ 24, 8, gSignalName_TransmissionCurrentGear, 1, -125, canIntel, canUint, 125, -125, 0};
static CanSignal *ETC2_arraySignals[ETC2_NumberOfSignals] = {&TransmissionCurrentGear};
messageNameCharStruct gMessageName_ETC2{"ETC2",MAX_LENGTH_NAME};
static CanMessageRx ETC2(gMessageName_ETC2, ETC2_arraySignals, ETC2_NumberOfSignals, 0x18F0055B, 8, 50);

const uint8_t FS1_NumberOfSignals = 8;
signalNameCharStruct gSignalName_EmergHammer_1{"EmergHammer_1",MAX_LENGTH_NAME};
static CanSignal EmergHammer_1{ 16, 2, gSignalName_EmergHammer_1, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_EmergHammer_2{"EmergHammer_2",MAX_LENGTH_NAME};
static CanSignal EmergHammer_2{ 18, 2, gSignalName_EmergHammer_2, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_EmergHammer_3{"EmergHammer_3",MAX_LENGTH_NAME};
static CanSignal EmergHammer_3{ 20, 2, gSignalName_EmergHammer_3, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_EmergHammer_4{"EmergHammer_4",MAX_LENGTH_NAME};
static CanSignal EmergHammer_4{ 22, 2, gSignalName_EmergHammer_4, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_FireExting_1{"FireExting_1",MAX_LENGTH_NAME};
static CanSignal FireExting_1{ 0, 2, gSignalName_FireExting_1, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_FireExting_2{"FireExting_2",MAX_LENGTH_NAME};
static CanSignal FireExting_2{ 2, 2, gSignalName_FireExting_2, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_FireExting_3{"FireExting_3",MAX_LENGTH_NAME};
static CanSignal FireExting_3{ 4, 2, gSignalName_FireExting_3, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_FireExting_4{"FireExting_4",MAX_LENGTH_NAME};
static CanSignal FireExting_4{ 6, 2, gSignalName_FireExting_4, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *FS1_arraySignals[FS1_NumberOfSignals] = {&EmergHammer_1, &EmergHammer_2, &EmergHammer_3, &EmergHammer_4, &FireExting_1, &FireExting_2, &FireExting_3, &FireExting_4};
messageNameCharStruct gMessageName_FS1{"FS1",MAX_LENGTH_NAME};
static CanMessageRx FS1(gMessageName_FS1, FS1_arraySignals, FS1_NumberOfSignals, 0x18FF505D, 8, 200);

const uint8_t LD_NumberOfSignals = 9;
signalNameCharStruct gSignalName_FrontFogLight{"FrontFogLight",MAX_LENGTH_NAME};
static CanSignal FrontFogLight{ 8, 2, gSignalName_FrontFogLight, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_HighBeamHeadLight{"HighBeamHeadLight",MAX_LENGTH_NAME};
static CanSignal HighBeamHeadLight{ 6, 2, gSignalName_HighBeamHeadLight, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_ImplementOEMOption1Light{"ImplementOEMOption1Light",MAX_LENGTH_NAME};
static CanSignal ImplementOEMOption1Light{ 50, 2, gSignalName_ImplementOEMOption1Light, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_LeftTurnSignalLight{"LeftTurnSignalLight",MAX_LENGTH_NAME};
static CanSignal LeftTurnSignalLight{ 14, 2, gSignalName_LeftTurnSignalLight, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_LowBeamHeadLight{"LowBeamHeadLight",MAX_LENGTH_NAME};
static CanSignal LowBeamHeadLight{ 4, 2, gSignalName_LowBeamHeadLight, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_MarkerLight{"MarkerLight",MAX_LENGTH_NAME};
static CanSignal MarkerLight{ 30, 2, gSignalName_MarkerLight, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_RearFogLight{"RearFogLight",MAX_LENGTH_NAME};
static CanSignal RearFogLight{ 32, 2, gSignalName_RearFogLight, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_RightTurnSignalLight{"RightTurnSignalLight",MAX_LENGTH_NAME};
static CanSignal RightTurnSignalLight{ 12, 2, gSignalName_RightTurnSignalLight, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_RunningLight{"RunningLight",MAX_LENGTH_NAME};
static CanSignal RunningLight{ 0, 2, gSignalName_RunningLight, 1, 0, canIntel, canUint, 3, 0, 0};
static CanSignal *LD_arraySignals[LD_NumberOfSignals] = {&FrontFogLight, &HighBeamHeadLight, &ImplementOEMOption1Light, &LeftTurnSignalLight, &LowBeamHeadLight, &MarkerLight, &RearFogLight, &RightTurnSignalLight, &RunningLight};
messageNameCharStruct gMessageName_LD{"LD",MAX_LENGTH_NAME};
static CanMessageRx LD(gMessageName_LD, LD_arraySignals, LD_NumberOfSignals, 0x18FE401E, 8, 500);

const uint8_t LD_2_NumberOfSignals = 1;
signalNameCharStruct gSignalName_LowBeamLightAuto{"LowBeamLightAuto",MAX_LENGTH_NAME};
static CanSignal LowBeamLightAuto{ 4, 2, gSignalName_LowBeamLightAuto, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *LD_2_arraySignals[LD_2_NumberOfSignals] = {&LowBeamLightAuto};
messageNameCharStruct gMessageName_LD_2{"LD_2",MAX_LENGTH_NAME};
static CanMessageRx LD_2(gMessageName_LD_2, LD_2_arraySignals, LD_2_NumberOfSignals, 0x0CFE4189, 8, 1000);

const uint8_t Motor_1_NumberOfSignals = 4;
signalNameCharStruct gSignalName_BatteryError{"BatteryError",MAX_LENGTH_NAME};
static CanSignal BatteryError{ 16, 2, gSignalName_BatteryError, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_MotorError{"MotorError",MAX_LENGTH_NAME};
static CanSignal MotorError{ 4, 2, gSignalName_MotorError, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_MotorWarning{"MotorWarning",MAX_LENGTH_NAME};
static CanSignal MotorWarning{ 2, 2, gSignalName_MotorWarning, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_ReadyToMove{"ReadyToMove",MAX_LENGTH_NAME};
static CanSignal ReadyToMove{ 24, 2, gSignalName_ReadyToMove, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *Motor_1_arraySignals[Motor_1_NumberOfSignals] = {&BatteryError, &MotorError, &MotorWarning, &ReadyToMove};
messageNameCharStruct gMessageName_Motor_1{"Motor_1",MAX_LENGTH_NAME};
static CanMessageRx Motor_1(gMessageName_Motor_1, Motor_1_arraySignals, Motor_1_NumberOfSignals, 0x18FD075B, 8, 1000);

const uint8_t OWW_NumberOfSignals = 3;
signalNameCharStruct gSignalName_FrontNonOperatorWiperSwitch{"FrontNonOperatorWiperSwitch",MAX_LENGTH_NAME};
static CanSignal FrontNonOperatorWiperSwitch{ 0, 4, gSignalName_FrontNonOperatorWiperSwitch, 1, 0, canIntel, canUint, 15, 0, 0};
signalNameCharStruct gSignalName_FrontOperatorWiperSwitch{"FrontOperatorWiperSwitch",MAX_LENGTH_NAME};
static CanSignal FrontOperatorWiperSwitch{ 4, 4, gSignalName_FrontOperatorWiperSwitch, 1, 0, canIntel, canUint, 15, 0, 0};
signalNameCharStruct gSignalName_WindshieldWasherOn{"WindshieldWasherOn",MAX_LENGTH_NAME};
static CanSignal WindshieldWasherOn{ 45, 3, gSignalName_WindshieldWasherOn, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *OWW_arraySignals[OWW_NumberOfSignals] = {&FrontNonOperatorWiperSwitch, &FrontOperatorWiperSwitch, &WindshieldWasherOn};
messageNameCharStruct gMessageName_OWW{"OWW",MAX_LENGTH_NAME};
static CanMessageRx OWW(gMessageName_OWW, OWW_arraySignals, OWW_NumberOfSignals, 0x18FDCD1E, 8, 200);

const uint8_t SCU2CLM_NumberOfSignals = 1;
signalNameCharStruct gSignalName_HeatingWheel{"HeatingWheel",MAX_LENGTH_NAME};
static CanSignal HeatingWheel{ 6, 2, gSignalName_HeatingWheel, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *SCU2CLM_arraySignals[SCU2CLM_NumberOfSignals] = {&HeatingWheel};
messageNameCharStruct gMessageName_SCU2CLM{"SCU2CLM",MAX_LENGTH_NAME};
static CanMessageRx SCU2CLM(gMessageName_SCU2CLM, SCU2CLM_arraySignals, SCU2CLM_NumberOfSignals, 0x18FF114D, 8, 50);

const uint8_t TCO1_NumberOfSignals = 14;
signalNameCharStruct gSignalName_DirectionIndicator{"DirectionIndicator",MAX_LENGTH_NAME};
static CanSignal DirectionIndicator{ 30, 2, gSignalName_DirectionIndicator, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_Driver1TimeRelatedStates{"Driver1TimeRelatedStates",MAX_LENGTH_NAME};
static CanSignal Driver1TimeRelatedStates{ 8, 4, gSignalName_Driver1TimeRelatedStates, 1, 0, canIntel, canUint, 15, 0, 0};
signalNameCharStruct gSignalName_Driver1WorkingState{"Driver1WorkingState",MAX_LENGTH_NAME};
static CanSignal Driver1WorkingState{ 0, 3, gSignalName_Driver1WorkingState, 1, 0, canIntel, canUint, 7, 0, 0};
signalNameCharStruct gSignalName_Driver2TimeRelatedStates{"Driver2TimeRelatedStates",MAX_LENGTH_NAME};
static CanSignal Driver2TimeRelatedStates{ 16, 4, gSignalName_Driver2TimeRelatedStates, 1, 0, canIntel, canUint, 15, 0, 0};
signalNameCharStruct gSignalName_Driver2WorkingState{"Driver2WorkingState",MAX_LENGTH_NAME};
static CanSignal Driver2WorkingState{ 3, 3, gSignalName_Driver2WorkingState, 1, 0, canIntel, canUint, 7, 0, 0};
signalNameCharStruct gSignalName_DriverCard_Driver1{"DriverCard_Driver1",MAX_LENGTH_NAME};
static CanSignal DriverCard_Driver1{ 12, 2, gSignalName_DriverCard_Driver1, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_DriverCard_Driver2{"DriverCard_Driver2",MAX_LENGTH_NAME};
static CanSignal DriverCard_Driver2{ 20, 2, gSignalName_DriverCard_Driver2, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_HandlingInformation{"HandlingInformation",MAX_LENGTH_NAME};
static CanSignal HandlingInformation{ 26, 2, gSignalName_HandlingInformation, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_SystemEvent{"SystemEvent",MAX_LENGTH_NAME};
static CanSignal SystemEvent{ 24, 2, gSignalName_SystemEvent, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_TachographOutputShaftSpeed{"TachographOutputShaftSpeed",MAX_LENGTH_NAME};
static CanSignal TachographOutputShaftSpeed{ 32, 16, gSignalName_TachographOutputShaftSpeed, 0.125, 0, canIntel, canUint, 8031.88, 0, 0};
signalNameCharStruct gSignalName_TachographPerformance{"TachographPerformance",MAX_LENGTH_NAME};
static CanSignal TachographPerformance{ 28, 2, gSignalName_TachographPerformance, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_TachographVehicleSpeed{"TachographVehicleSpeed",MAX_LENGTH_NAME};
static CanSignal TachographVehicleSpeed{ 48, 16, gSignalName_TachographVehicleSpeed, 0.00390625, 0, canIntel, canUint, 250.996, 0, 0};
signalNameCharStruct gSignalName_VehicleMotion{"VehicleMotion",MAX_LENGTH_NAME};
static CanSignal VehicleMotion{ 6, 2, gSignalName_VehicleMotion, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_VehicleOverspeed{"VehicleOverspeed",MAX_LENGTH_NAME};
static CanSignal VehicleOverspeed{ 14, 2, gSignalName_VehicleOverspeed, 1, 0, canIntel, canUint, 3, 0, 0};
static CanSignal *TCO1_arraySignals[TCO1_NumberOfSignals] = {&DirectionIndicator, &Driver1TimeRelatedStates, &Driver1WorkingState, &Driver2TimeRelatedStates, &Driver2WorkingState, &DriverCard_Driver1, &DriverCard_Driver2, &HandlingInformation, &SystemEvent, &TachographOutputShaftSpeed, &TachographPerformance, &TachographVehicleSpeed, &VehicleMotion, &VehicleOverspeed};
messageNameCharStruct gMessageName_TCO1{"TCO1",MAX_LENGTH_NAME};
static CanMessageRx TCO1(gMessageName_TCO1, TCO1_arraySignals, TCO1_NumberOfSignals, 0x0CFE6C18, 8, 50);

const uint8_t TCO1_EE_NumberOfSignals = 1;
signalNameCharStruct gSignalName_TcoVehicleSpeed{"TcoVehicleSpeed",MAX_LENGTH_NAME};
static CanSignal TcoVehicleSpeed{ 48, 16, gSignalName_TcoVehicleSpeed, 390625, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *TCO1_EE_arraySignals[TCO1_EE_NumberOfSignals] = {&TcoVehicleSpeed};
messageNameCharStruct gMessageName_TCO1_EE{"TCO1_EE",MAX_LENGTH_NAME};
static CanMessageRx TCO1_EE(gMessageName_TCO1_EE, TCO1_EE_arraySignals, TCO1_EE_NumberOfSignals, 0x18FE6CEE, 8, 50);

const uint8_t TIRE_NumberOfSignals = 4;
signalNameCharStruct gSignalName_TireAxis{"TireAxis",MAX_LENGTH_NAME};
static CanSignal TireAxis{ 4, 4, gSignalName_TireAxis, 1, 0, canIntel, canUint, 15, 0, 0};
signalNameCharStruct gSignalName_TireLocation{"TireLocation",MAX_LENGTH_NAME};
static CanSignal TireLocation{ 0, 4, gSignalName_TireLocation, 1, 0, canIntel, canUint, 15, 0, 0};
signalNameCharStruct gSignalName_TirePressure{"TirePressure",MAX_LENGTH_NAME};
static CanSignal TirePressure{ 40, 8, gSignalName_TirePressure, 5.5, -101.3, canIntel, canUint, 1400, 100, 0};
signalNameCharStruct gSignalName_TireTemp{"TireTemp",MAX_LENGTH_NAME};
static CanSignal TireTemp{ 48, 8, gSignalName_TireTemp, 1, -50, canIntel, canUint, 250, -50, 0};
static CanSignal *TIRE_arraySignals[TIRE_NumberOfSignals] = {&TireAxis, &TireLocation, &TirePressure, &TireTemp};
messageNameCharStruct gMessageName_TIRE{"TIRE",MAX_LENGTH_NAME};
static CanMessageRx TIRE(gMessageName_TIRE, TIRE_arraySignals, TIRE_NumberOfSignals, 0x18FEF433, 8, 10000);

const uint8_t TMS_NumberOfSignals = 2;
signalNameCharStruct gSignalName_TmsError{"TmsError",MAX_LENGTH_NAME};
static CanSignal TmsError{ 32, 6, gSignalName_TmsError, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_TmsMode{"TmsMode",MAX_LENGTH_NAME};
static CanSignal TmsMode{ 17, 3, gSignalName_TmsMode, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *TMS_arraySignals[TMS_NumberOfSignals] = {&TmsError, &TmsMode};
messageNameCharStruct gMessageName_TMS{"TMS",MAX_LENGTH_NAME};
static CanMessageRx TMS(gMessageName_TMS, TMS_arraySignals, TMS_NumberOfSignals, 0x18FFF345, 8, 500);

const uint8_t VDHR_NumberOfSignals = 2;
signalNameCharStruct gSignalName_TotalVehicleDistance{"TotalVehicleDistance",MAX_LENGTH_NAME};
static CanSignal TotalVehicleDistance{ 0, 32, gSignalName_TotalVehicleDistance, 0.005, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_TripDistance{"TripDistance",MAX_LENGTH_NAME};
static CanSignal TripDistance{ 32, 32, gSignalName_TripDistance, 0.005, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *VDHR_arraySignals[VDHR_NumberOfSignals] = {&TotalVehicleDistance, &TripDistance};
messageNameCharStruct gMessageName_VDHR{"VDHR",MAX_LENGTH_NAME};
static CanMessageRx VDHR(gMessageName_VDHR, VDHR_arraySignals, VDHR_NumberOfSignals, 0x18FEC1EE, 8, 1000);

const uint8_t VEP1_NumberOfSignals = 1;
signalNameCharStruct gSignalName_ActualVoltage_24v{"ActualVoltage_24v",MAX_LENGTH_NAME};
static CanSignal ActualVoltage_24v{ 32, 16, gSignalName_ActualVoltage_24v, 0.05, 0, canIntel, canUint, 3212.75, 0, 0};
static CanSignal *VEP1_arraySignals[VEP1_NumberOfSignals] = {&ActualVoltage_24v};
messageNameCharStruct gMessageName_VEP1{"VEP1",MAX_LENGTH_NAME};
static CanMessageRx VEP1(gMessageName_VEP1, VEP1_arraySignals, VEP1_NumberOfSignals, 0x18FEF71E, 8, 1000);

const uint8_t DB_1_NumberOfSignals = 12;
signalNameCharStruct gSignalName_BtnBackAns{"BtnBackAns",MAX_LENGTH_NAME};
static CanSignal BtnBackAns{ 50, 2, gSignalName_BtnBackAns, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_BtnMinusAns{"BtnMinusAns",MAX_LENGTH_NAME};
static CanSignal BtnMinusAns{ 52, 2, gSignalName_BtnMinusAns, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_BtnOkAns{"BtnOkAns",MAX_LENGTH_NAME};
static CanSignal BtnOkAns{ 48, 2, gSignalName_BtnOkAns, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_BtnPlusAns{"BtnPlusAns",MAX_LENGTH_NAME};
static CanSignal BtnPlusAns{ 54, 2, gSignalName_BtnPlusAns, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_HearthBeat{"HearthBeat",MAX_LENGTH_NAME};
static CanSignal HearthBeat{ 0, 2, gSignalName_HearthBeat, 1, 0, canIntel, canUint, 3, 0, 0};
signalNameCharStruct gSignalName_IpAddressByte_1{"IpAddressByte_1",MAX_LENGTH_NAME};
static CanSignal IpAddressByte_1{ 8, 8, gSignalName_IpAddressByte_1, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_IpAddressByte_2{"IpAddressByte_2",MAX_LENGTH_NAME};
static CanSignal IpAddressByte_2{ 16, 8, gSignalName_IpAddressByte_2, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_IpAddressByte_3{"IpAddressByte_3",MAX_LENGTH_NAME};
static CanSignal IpAddressByte_3{ 24, 8, gSignalName_IpAddressByte_3, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_IpAddressByte_4{"IpAddressByte_4",MAX_LENGTH_NAME};
static CanSignal IpAddressByte_4{ 32, 8, gSignalName_IpAddressByte_4, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_ProgramBuild{"ProgramBuild",MAX_LENGTH_NAME};
static CanSignal ProgramBuild{ 56, 8, gSignalName_ProgramBuild, 1, 0, canIntel, canUint, 250, 0, 0};
signalNameCharStruct gSignalName_ProgramSubVersion{"ProgramSubVersion",MAX_LENGTH_NAME};
static CanSignal ProgramSubVersion{ 40, 6, gSignalName_ProgramSubVersion, 1, 0, canIntel, canUint, 63, 0, 0};
signalNameCharStruct gSignalName_ProgramVersion{"ProgramVersion",MAX_LENGTH_NAME};
static CanSignal ProgramVersion{ 2, 6, gSignalName_ProgramVersion, 1, 0, canIntel, canUint, 63, 0, 0};
static CanSignal *DB_1_arraySignals[DB_1_NumberOfSignals] = {&BtnBackAns, &BtnMinusAns, &BtnOkAns, &BtnPlusAns, &HearthBeat, &IpAddressByte_1, &IpAddressByte_2, &IpAddressByte_3, &IpAddressByte_4, &ProgramBuild, &ProgramSubVersion, &ProgramVersion};
messageNameCharStruct gMessageName_DB_1{"DB_1",MAX_LENGTH_NAME};
static CanMessageTx DB_1(gMessageName_DB_1, DB_1_arraySignals, DB_1_NumberOfSignals, 0x18FF1017, 8, 1000);

const uint8_t DB_2_NumberOfSignals = 5;
signalNameCharStruct gSignalName_AutoClossingDoors{"AutoClossingDoors",MAX_LENGTH_NAME};
static CanSignal AutoClossingDoors{ 4, 2, gSignalName_AutoClossingDoors, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_CpuLoad{"CpuLoad",MAX_LENGTH_NAME};
static CanSignal CpuLoad{ 48, 8, gSignalName_CpuLoad, 0.4, 0, canIntel, canUint, 100, 0, 0};
signalNameCharStruct gSignalName_DisableSafety{"DisableSafety",MAX_LENGTH_NAME};
static CanSignal DisableSafety{ 2, 2, gSignalName_DisableSafety, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_MemLoad{"MemLoad",MAX_LENGTH_NAME};
static CanSignal MemLoad{ 56, 8, gSignalName_MemLoad, 0.4, 0, canIntel, canUint, 100, 0, 0};
signalNameCharStruct gSignalName_PassengerDoorControl{"PassengerDoorControl",MAX_LENGTH_NAME};
static CanSignal PassengerDoorControl{ 0, 2, gSignalName_PassengerDoorControl, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DB_2_arraySignals[DB_2_NumberOfSignals] = {&AutoClossingDoors, &CpuLoad, &DisableSafety, &MemLoad, &PassengerDoorControl};
messageNameCharStruct gMessageName_DB_2{"DB_2",MAX_LENGTH_NAME};
static CanMessageTx DB_2(gMessageName_DB_2, DB_2_arraySignals, DB_2_NumberOfSignals, 0x18FFA017, 8, 100);

const uint8_t DB_3_NumberOfSignals = 2;
signalNameCharStruct gSignalName_TurnLeftLamp{"TurnLeftLamp",MAX_LENGTH_NAME};
static CanSignal TurnLeftLamp{ 2, 2, gSignalName_TurnLeftLamp, 1, 0, canIntel, canUint, 0, 0, 0};
signalNameCharStruct gSignalName_TurnRightLamp{"TurnRightLamp",MAX_LENGTH_NAME};
static CanSignal TurnRightLamp{ 0, 2, gSignalName_TurnRightLamp, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DB_3_arraySignals[DB_3_NumberOfSignals] = {&TurnLeftLamp, &TurnRightLamp};
messageNameCharStruct gMessageName_DB_3{"DB_3",MAX_LENGTH_NAME};
static CanMessageTx DB_3(gMessageName_DB_3, DB_3_arraySignals, DB_3_NumberOfSignals, 0x18FF1117, 8, 0);

const uint8_t numberOfRxMessages = 47;
static CanMessageRx *arrayRxMessages[numberOfRxMessages] = { &ADAS_1, &AIR1, &AMB, &ASC1, &ASC2, &BDS, &CCUT1, &CCVS1, &CCVS1_03, &CDC, &CECU_06, &CECU_A0, &CECU_A1, &CL, &CM1, &CM1_E1, &DC1, &DC2, &DCU1, &DCU2, &DCU3, &DD1_12, &DD1_1E, &DLDC1, &DM1_EBS, &DM1_EPB, &EBC1, &EBC4, &EBC5, &ECO, &EDSC2_2, &ELECTRO_1, &EPBS1, &ET1, &ETC2, &FS1, &LD, &LD_2, &Motor_1, &OWW, &SCU2CLM, &TCO1, &TCO1_EE, &TIRE, &TMS, &VDHR, &VEP1};
const uint8_t numberOfTxMessages = 3;
static CanMessageTx *arrayTxMessages[numberOfTxMessages] = { &DB_1, &DB_2, &DB_3};
CanDataBase gCanDB(arrayRxMessages,numberOfRxMessages,arrayTxMessages,numberOfTxMessages);
