//C:/Users/user/workspace/python/CanAst/dbcFiles/Dashboard_PazNG_v1.1.0.dbc, последние изменения Wed Apr 23 14:44:24 2025
#include "canDataBase/canDataBase.h"

using namespace canBus;

canSignalStateStruct gCanSignalState;

const uint8_t ADAS_1_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_BlindSpot{"BlindSpot",MAX_LENGTH_NAME};
static CanSignal BlindSpot{ 32, 8, gSignalName_BlindSpot, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ADAS_1_arraySignals[ADAS_1_NumberOfSignals] = {&BlindSpot};
const messageNameCharStruct gMessageName_ADAS_1{"ADAS_1",MAX_LENGTH_NAME};
static CanMessageRx ADAS_1(gMessageName_ADAS_1, ADAS_1_arraySignals, ADAS_1_NumberOfSignals, 0x18A9175D, 8, 0);

const uint8_t AIR1_NumberOfSignals = 6;
const signalNameCharStruct gSignalName_AirCompressorStatus{"AirCompressorStatus",MAX_LENGTH_NAME};
static CanSignal AirCompressorStatus{ 48, 2, gSignalName_AirCompressorStatus, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_AirSuspensionSupplyPressure{"AirSuspensionSupplyPressure",MAX_LENGTH_NAME};
static CanSignal AirSuspensionSupplyPressure{ 40, 8, gSignalName_AirSuspensionSupplyPressure, 8, 0, canIntel, canUint, 2000, 0, 0};
const signalNameCharStruct gSignalName_AuxiliaryEquipmentSupplyPressure{"AuxiliaryEquipmentSupplyPressure",MAX_LENGTH_NAME};
static CanSignal AuxiliaryEquipmentSupplyPressure{ 32, 8, gSignalName_AuxiliaryEquipmentSupplyPressure, 8, 0, canIntel, canUint, 2000, 0, 0};
const signalNameCharStruct gSignalName_ParkingAirPressure{"ParkingAirPressure",MAX_LENGTH_NAME};
static CanSignal ParkingAirPressure{ 8, 8, gSignalName_ParkingAirPressure, 8, 0, canIntel, canUint, 2000, 0, 0};
const signalNameCharStruct gSignalName_ServiceBrakeCircuit1AirPress{"ServiceBrakeCircuit1AirPress",MAX_LENGTH_NAME};
static CanSignal ServiceBrakeCircuit1AirPress{ 16, 8, gSignalName_ServiceBrakeCircuit1AirPress, 8, 0, canIntel, canUint, 2000, 0, 0};
const signalNameCharStruct gSignalName_ServiceBrakeCircuit2AirPress{"ServiceBrakeCircuit2AirPress",MAX_LENGTH_NAME};
static CanSignal ServiceBrakeCircuit2AirPress{ 24, 8, gSignalName_ServiceBrakeCircuit2AirPress, 8, 0, canIntel, canUint, 2000, 0, 0};
static CanSignal *AIR1_arraySignals[AIR1_NumberOfSignals] = {&AirCompressorStatus, &AirSuspensionSupplyPressure, &AuxiliaryEquipmentSupplyPressure, &ParkingAirPressure, &ServiceBrakeCircuit1AirPress, &ServiceBrakeCircuit2AirPress};
const messageNameCharStruct gMessageName_AIR1{"AIR1",MAX_LENGTH_NAME};
static CanMessageRx AIR1(gMessageName_AIR1, AIR1_arraySignals, AIR1_NumberOfSignals, 0x18FEAE30, 8, 100);

const uint8_t AMB_NumberOfSignals = 3;
const signalNameCharStruct gSignalName_AmbientAirTemp{"AmbientAirTemp",MAX_LENGTH_NAME};
static CanSignal AmbientAirTemp{ 24, 16, gSignalName_AmbientAirTemp, 0.03125, -273, canIntel, canUint, 1734.96875, -273, 0};
const signalNameCharStruct gSignalName_CabInteriorTempA{"CabInteriorTempA",MAX_LENGTH_NAME};
static CanSignal CabInteriorTempA{ 8, 16, gSignalName_CabInteriorTempA, 0.03125, -273, canIntel, canUint, 1734.97, -273, 0};
const signalNameCharStruct gSignalName_CabInteriorTempB{"CabInteriorTempB",MAX_LENGTH_NAME};
static CanSignal CabInteriorTempB{ 40, 16, gSignalName_CabInteriorTempB, 0.03125, -273, canIntel, canUint, 1734.97, -273, 0};
static CanSignal *AMB_arraySignals[AMB_NumberOfSignals] = {&AmbientAirTemp, &CabInteriorTempA, &CabInteriorTempB};
const messageNameCharStruct gMessageName_AMB{"AMB",MAX_LENGTH_NAME};
static CanMessageRx AMB(gMessageName_AMB, AMB_arraySignals, AMB_NumberOfSignals, 0x18FEF53A, 8, 1000);

const uint8_t ASC1_NumberOfSignals = 11;
const signalNameCharStruct gSignalName_AboveNominalLevelFrontAxle{"AboveNominalLevelFrontAxle",MAX_LENGTH_NAME};
static CanSignal AboveNominalLevelFrontAxle{ 12, 2, gSignalName_AboveNominalLevelFrontAxle, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_AboveNominalLevelRearAxle{"AboveNominalLevelRearAxle",MAX_LENGTH_NAME};
static CanSignal AboveNominalLevelRearAxle{ 14, 2, gSignalName_AboveNominalLevelRearAxle, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_BelowNominalLevelFrontAxle{"BelowNominalLevelFrontAxle",MAX_LENGTH_NAME};
static CanSignal BelowNominalLevelFrontAxle{ 8, 2, gSignalName_BelowNominalLevelFrontAxle, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_BelowNominalLevelRearAxle{"BelowNominalLevelRearAxle",MAX_LENGTH_NAME};
static CanSignal BelowNominalLevelRearAxle{ 10, 2, gSignalName_BelowNominalLevelRearAxle, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_KneelingInformation{"KneelingInformation",MAX_LENGTH_NAME};
static CanSignal KneelingInformation{ 24, 4, gSignalName_KneelingInformation, 1, 0, canIntel, canUint, 15, 0, 0};
const signalNameCharStruct gSignalName_LiftingControlModeFrontAxle{"LiftingControlModeFrontAxle",MAX_LENGTH_NAME};
static CanSignal LiftingControlModeFrontAxle{ 20, 2, gSignalName_LiftingControlModeFrontAxle, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_LiftingControlModeRearAxle{"LiftingControlModeRearAxle",MAX_LENGTH_NAME};
static CanSignal LiftingControlModeRearAxle{ 22, 2, gSignalName_LiftingControlModeRearAxle, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_LoweringControlModeFrontAxle{"LoweringControlModeFrontAxle",MAX_LENGTH_NAME};
static CanSignal LoweringControlModeFrontAxle{ 16, 2, gSignalName_LoweringControlModeFrontAxle, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_LoweringControlModeRearAxle{"LoweringControlModeRearAxle",MAX_LENGTH_NAME};
static CanSignal LoweringControlModeRearAxle{ 18, 2, gSignalName_LoweringControlModeRearAxle, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_NominalLevelFrontAxle{"NominalLevelFrontAxle",MAX_LENGTH_NAME};
static CanSignal NominalLevelFrontAxle{ 0, 4, gSignalName_NominalLevelFrontAxle, 1, 0, canIntel, canUint, 15, 0, 0};
const signalNameCharStruct gSignalName_NominalLevelRearAxle{"NominalLevelRearAxle",MAX_LENGTH_NAME};
static CanSignal NominalLevelRearAxle{ 4, 4, gSignalName_NominalLevelRearAxle, 1, 0, canIntel, canUint, 15, 0, 0};
static CanSignal *ASC1_arraySignals[ASC1_NumberOfSignals] = {&AboveNominalLevelFrontAxle, &AboveNominalLevelRearAxle, &BelowNominalLevelFrontAxle, &BelowNominalLevelRearAxle, &KneelingInformation, &LiftingControlModeFrontAxle, &LiftingControlModeRearAxle, &LoweringControlModeFrontAxle, &LoweringControlModeRearAxle, &NominalLevelFrontAxle, &NominalLevelRearAxle};
const messageNameCharStruct gMessageName_ASC1{"ASC1",MAX_LENGTH_NAME};
static CanMessageRx ASC1(gMessageName_ASC1, ASC1_arraySignals, ASC1_NumberOfSignals, 0x0CFE5A2F, 8, 100);

const uint8_t ASC2_Rx_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_AutoKneeling{"AutoKneeling",MAX_LENGTH_NAME};
static CanSignal AutoKneeling{ 6, 2, gSignalName_AutoKneeling, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ASC2_Rx_arraySignals[ASC2_Rx_NumberOfSignals] = {&AutoKneeling};
const messageNameCharStruct gMessageName_ASC2_Rx{"ASC2_Rx",MAX_LENGTH_NAME};
static CanMessageRx ASC2_Rx(gMessageName_ASC2_Rx, ASC2_Rx_arraySignals, ASC2_Rx_NumberOfSignals, 0x0CD22F27, 8, 100);

const uint8_t AUXIO_R_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_Aux2{"Aux2",MAX_LENGTH_NAME};
static CanSignal Aux2{ 26, 2, gSignalName_Aux2, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *AUXIO_R_arraySignals[AUXIO_R_NumberOfSignals] = {&Aux2};
const messageNameCharStruct gMessageName_AUXIO_R{"AUXIO_R",MAX_LENGTH_NAME};
static CanMessageRx AUXIO_R(gMessageName_AUXIO_R, AUXIO_R_arraySignals, AUXIO_R_NumberOfSignals, 0x18FED91E, 8, 0);

const uint8_t BCH1_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_BatteryCharger1State{"BatteryCharger1State",MAX_LENGTH_NAME};
static CanSignal BatteryCharger1State{ 0, 4, gSignalName_BatteryCharger1State, 1, 0, canIntel, canUint, 15, 0, 0};
static CanSignal *BCH1_arraySignals[BCH1_NumberOfSignals] = {&BatteryCharger1State};
const messageNameCharStruct gMessageName_BCH1{"BCH1",MAX_LENGTH_NAME};
static CanMessageRx BCH1(gMessageName_BCH1, BCH1_arraySignals, BCH1_NumberOfSignals, 0x18FD155B, 8, 1000);

const uint8_t BDS_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_SeatBeltSwitch{"SeatBeltSwitch",MAX_LENGTH_NAME};
static CanSignal SeatBeltSwitch{ 0, 2, gSignalName_SeatBeltSwitch, 1, 0, canIntel, canUint, 3, 0, 0};
static CanSignal *BDS_arraySignals[BDS_NumberOfSignals] = {&SeatBeltSwitch};
const messageNameCharStruct gMessageName_BDS{"BDS",MAX_LENGTH_NAME};
static CanMessageRx BDS(gMessageName_BDS, BDS_arraySignals, BDS_NumberOfSignals, 0x14FD171E, 8, 50);

const uint8_t BJM1_NumberOfSignals = 7;
const signalNameCharStruct gSignalName_Btn12_Menu{"Btn12_Menu",MAX_LENGTH_NAME};
static CanSignal Btn12_Menu{ 56, 2, gSignalName_Btn12_Menu, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Btn1_Ok{"Btn1_Ok",MAX_LENGTH_NAME};
static CanSignal Btn1_Ok{ 46, 2, gSignalName_Btn1_Ok, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Btn2_Back{"Btn2_Back",MAX_LENGTH_NAME};
static CanSignal Btn2_Back{ 44, 2, gSignalName_Btn2_Back, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Btn3_Left{"Btn3_Left",MAX_LENGTH_NAME};
static CanSignal Btn3_Left{ 42, 2, gSignalName_Btn3_Left, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Btn4_Right{"Btn4_Right",MAX_LENGTH_NAME};
static CanSignal Btn4_Right{ 40, 2, gSignalName_Btn4_Right, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Btn5_Vol_P{"Btn5_Vol_P",MAX_LENGTH_NAME};
static CanSignal Btn5_Vol_P{ 54, 2, gSignalName_Btn5_Vol_P, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Btn6_Vol_M{"Btn6_Vol_M",MAX_LENGTH_NAME};
static CanSignal Btn6_Vol_M{ 52, 2, gSignalName_Btn6_Vol_M, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *BJM1_arraySignals[BJM1_NumberOfSignals] = {&Btn12_Menu, &Btn1_Ok, &Btn2_Back, &Btn3_Left, &Btn4_Right, &Btn5_Vol_P, &Btn6_Vol_M};
const messageNameCharStruct gMessageName_BJM1{"BJM1",MAX_LENGTH_NAME};
static CanMessageRx BJM1(gMessageName_BJM1, BJM1_arraySignals, BJM1_NumberOfSignals, 0x0CFDD61E, 8, 100);

const uint8_t CCU1_DB_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_EstimatedRange{"EstimatedRange",MAX_LENGTH_NAME};
static CanSignal EstimatedRange{ 16, 8, gSignalName_EstimatedRange, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CCU1_DB_arraySignals[CCU1_DB_NumberOfSignals] = {&EstimatedRange};
const messageNameCharStruct gMessageName_CCU1_DB{"CCU1_DB",MAX_LENGTH_NAME};
static CanMessageRx CCU1_DB(gMessageName_CCU1_DB, CCU1_DB_arraySignals, CCU1_DB_NumberOfSignals, 0x1830A03A, 8, 1000);

const uint8_t CCUT1_NumberOfSignals = 4;
const signalNameCharStruct gSignalName_RoofTemp{"RoofTemp",MAX_LENGTH_NAME};
static CanSignal RoofTemp{ 48, 8, gSignalName_RoofTemp, 1, -40, canIntel, canUint, 215, -40, 0};
const signalNameCharStruct gSignalName_SalonTemp_1{"SalonTemp_1",MAX_LENGTH_NAME};
static CanSignal SalonTemp_1{ 0, 8, gSignalName_SalonTemp_1, 1, -40, canIntel, canUint, 215, -40, 0};
const signalNameCharStruct gSignalName_SalonTemp_2{"SalonTemp_2",MAX_LENGTH_NAME};
static CanSignal SalonTemp_2{ 8, 8, gSignalName_SalonTemp_2, 1, -40, canIntel, canUint, 215, -40, 0};
const signalNameCharStruct gSignalName_SalonTemp_3{"SalonTemp_3",MAX_LENGTH_NAME};
static CanSignal SalonTemp_3{ 16, 8, gSignalName_SalonTemp_3, 1, -40, canIntel, canUint, 215, -40, 0};
static CanSignal *CCUT1_arraySignals[CCUT1_NumberOfSignals] = {&RoofTemp, &SalonTemp_1, &SalonTemp_2, &SalonTemp_3};
const messageNameCharStruct gMessageName_CCUT1{"CCUT1",MAX_LENGTH_NAME};
static CanMessageRx CCUT1(gMessageName_CCUT1, CCUT1_arraySignals, CCUT1_NumberOfSignals, 0x18FF0D3A, 8, 500);

const uint8_t CCVS1_NumberOfSignals = 3;
const signalNameCharStruct gSignalName_CruiseControl{"CruiseControl",MAX_LENGTH_NAME};
static CanSignal CruiseControl{ 24, 2, gSignalName_CruiseControl, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_ParkingBrakeState{"ParkingBrakeState",MAX_LENGTH_NAME};
static CanSignal ParkingBrakeState{ 2, 2, gSignalName_ParkingBrakeState, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_WheelBasedVehicleSpeed{"WheelBasedVehicleSpeed",MAX_LENGTH_NAME};
static CanSignal WheelBasedVehicleSpeed{ 8, 16, gSignalName_WheelBasedVehicleSpeed, 0.00390625, 0, canIntel, canUint, 250.996, 0, 0};
static CanSignal *CCVS1_arraySignals[CCVS1_NumberOfSignals] = {&CruiseControl, &ParkingBrakeState, &WheelBasedVehicleSpeed};
const messageNameCharStruct gMessageName_CCVS1{"CCVS1",MAX_LENGTH_NAME};
static CanMessageRx CCVS1(gMessageName_CCVS1, CCVS1_arraySignals, CCVS1_NumberOfSignals, 0x18FEF100, 8, 100);

const uint8_t CCVS1_03_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_VehicleSpeed_03{"VehicleSpeed_03",MAX_LENGTH_NAME};
static CanSignal VehicleSpeed_03{ 8, 16, gSignalName_VehicleSpeed_03, 0.00390625, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CCVS1_03_arraySignals[CCVS1_03_NumberOfSignals] = {&VehicleSpeed_03};
const messageNameCharStruct gMessageName_CCVS1_03{"CCVS1_03",MAX_LENGTH_NAME};
static CanMessageRx CCVS1_03(gMessageName_CCVS1_03, CCVS1_03_arraySignals, CCVS1_03_NumberOfSignals, 0x18FEF103, 8, 100);

const uint8_t CDC_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_MirrorHeatLeft{"MirrorHeatLeft",MAX_LENGTH_NAME};
static CanSignal MirrorHeatLeft{ 48, 2, gSignalName_MirrorHeatLeft, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_MirrorHeatRight{"MirrorHeatRight",MAX_LENGTH_NAME};
static CanSignal MirrorHeatRight{ 50, 2, gSignalName_MirrorHeatRight, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CDC_arraySignals[CDC_NumberOfSignals] = {&MirrorHeatLeft, &MirrorHeatRight};
const messageNameCharStruct gMessageName_CDC{"CDC",MAX_LENGTH_NAME};
static CanMessageRx CDC(gMessageName_CDC, CDC_arraySignals, CDC_NumberOfSignals, 0x14FC121E, 8, 100);

const uint8_t CL_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_SalonLightning{"SalonLightning",MAX_LENGTH_NAME};
static CanSignal SalonLightning{ 8, 8, gSignalName_SalonLightning, 0.4, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CL_arraySignals[CL_NumberOfSignals] = {&SalonLightning};
const messageNameCharStruct gMessageName_CL{"CL",MAX_LENGTH_NAME};
static CanMessageRx CL(gMessageName_CL, CL_arraySignals, CL_NumberOfSignals, 0x18D0171E, 8, 100);

const uint8_t CM1_NumberOfSignals = 4;
const signalNameCharStruct gSignalName_AuxHeaterCoolantPumpReq{"AuxHeaterCoolantPumpReq",MAX_LENGTH_NAME};
static CanSignal AuxHeaterCoolantPumpReq{ 24, 2, gSignalName_AuxHeaterCoolantPumpReq, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_AuxHeaterModeReq{"AuxHeaterModeReq",MAX_LENGTH_NAME};
static CanSignal AuxHeaterModeReq{ 48, 4, gSignalName_AuxHeaterModeReq, 1, 0, canIntel, canUint, 15, 0, 0};
const signalNameCharStruct gSignalName_OperatorSeatDirectionSwitch{"OperatorSeatDirectionSwitch",MAX_LENGTH_NAME};
static CanSignal OperatorSeatDirectionSwitch{ 28, 2, gSignalName_OperatorSeatDirectionSwitch, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_RequestedPercentFanSpeed{"RequestedPercentFanSpeed",MAX_LENGTH_NAME};
static CanSignal RequestedPercentFanSpeed{ 0, 8, gSignalName_RequestedPercentFanSpeed, 0.4, 0, canIntel, canUint, 100, 0, 0};
static CanSignal *CM1_arraySignals[CM1_NumberOfSignals] = {&AuxHeaterCoolantPumpReq, &AuxHeaterModeReq, &OperatorSeatDirectionSwitch, &RequestedPercentFanSpeed};
const messageNameCharStruct gMessageName_CM1{"CM1",MAX_LENGTH_NAME};
static CanMessageRx CM1(gMessageName_CM1, CM1_arraySignals, CM1_NumberOfSignals, 0x18FE171E, 8, 1000);

const uint8_t CM1_E1_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_HeaterLiquidState{"HeaterLiquidState",MAX_LENGTH_NAME};
static CanSignal HeaterLiquidState{ 48, 4, gSignalName_HeaterLiquidState, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *CM1_E1_arraySignals[CM1_E1_NumberOfSignals] = {&HeaterLiquidState};
const messageNameCharStruct gMessageName_CM1_E1{"CM1_E1",MAX_LENGTH_NAME};
static CanMessageRx CM1_E1(gMessageName_CM1_E1, CM1_E1_arraySignals, CM1_E1_NumberOfSignals, 0x18FE17E1, 8, 0);

const uint8_t DC1_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_RampError{"RampError",MAX_LENGTH_NAME};
static CanSignal RampError{ 4, 2, gSignalName_RampError, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DC1_arraySignals[DC1_NumberOfSignals] = {&RampError};
const messageNameCharStruct gMessageName_DC1{"DC1",MAX_LENGTH_NAME};
static CanMessageRx DC1(gMessageName_DC1, DC1_arraySignals, DC1_NumberOfSignals, 0x18FE4E1E, 8, 100);

const uint8_t DC2_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_EngineHatchOpen{"EngineHatchOpen",MAX_LENGTH_NAME};
static CanSignal EngineHatchOpen{ 26, 2, gSignalName_EngineHatchOpen, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DC2_arraySignals[DC2_NumberOfSignals] = {&EngineHatchOpen};
const messageNameCharStruct gMessageName_DC2{"DC2",MAX_LENGTH_NAME};
static CanMessageRx DC2(gMessageName_DC2, DC2_arraySignals, DC2_NumberOfSignals, 0x18FDA51E, 8, 100);

const uint8_t DD1_12_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_DD1_ReserveFuelLevel{"DD1_ReserveFuelLevel",MAX_LENGTH_NAME};
static CanSignal DD1_ReserveFuelLevel{ 8, 8, gSignalName_DD1_ReserveFuelLevel, 0.4, 0, canIntel, canUint, 100, 0, 0};
static CanSignal *DD1_12_arraySignals[DD1_12_NumberOfSignals] = {&DD1_ReserveFuelLevel};
const messageNameCharStruct gMessageName_DD1_12{"DD1_12",MAX_LENGTH_NAME};
static CanMessageRx DD1_12(gMessageName_DD1_12, DD1_12_arraySignals, DD1_12_NumberOfSignals, 0x18FEFC12, 8, 1000);

const uint8_t DD1_1E_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_CargoAmbientTemp{"CargoAmbientTemp",MAX_LENGTH_NAME};
static CanSignal CargoAmbientTemp{ 32, 16, gSignalName_CargoAmbientTemp, 1, -273, canIntel, canUint, 1734.96875, -273, 0};
const signalNameCharStruct gSignalName_DD1_WasherFluidLow{"DD1_WasherFluidLow",MAX_LENGTH_NAME};
static CanSignal DD1_WasherFluidLow{ 0, 8, gSignalName_DD1_WasherFluidLow, 0.4, 0, canIntel, canUint, 100, 0, 0};
static CanSignal *DD1_1E_arraySignals[DD1_1E_NumberOfSignals] = {&CargoAmbientTemp, &DD1_WasherFluidLow};
const messageNameCharStruct gMessageName_DD1_1E{"DD1_1E",MAX_LENGTH_NAME};
static CanMessageRx DD1_1E(gMessageName_DD1_1E, DD1_1E_arraySignals, DD1_1E_NumberOfSignals, 0x18FEFC1E, 8, 1000);

const uint8_t DLCC1_NumberOfSignals = 6;
const signalNameCharStruct gSignalName_EngineAmberWarningLC{"EngineAmberWarningLC",MAX_LENGTH_NAME};
static CanSignal EngineAmberWarningLC{ 2, 2, gSignalName_EngineAmberWarningLC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EngineCoolantLevelLowLC{"EngineCoolantLevelLowLC",MAX_LENGTH_NAME};
static CanSignal EngineCoolantLevelLowLC{ 16, 2, gSignalName_EngineCoolantLevelLowLC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EngineCoolantTempHighLC{"EngineCoolantTempHighLC",MAX_LENGTH_NAME};
static CanSignal EngineCoolantTempHighLC{ 14, 2, gSignalName_EngineCoolantTempHighLC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EngineRedStopLC{"EngineRedStopLC",MAX_LENGTH_NAME};
static CanSignal EngineRedStopLC{ 4, 2, gSignalName_EngineRedStopLC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_LowLevelSalonLiquid{"LowLevelSalonLiquid",MAX_LENGTH_NAME};
static CanSignal LowLevelSalonLiquid{ 50, 2, gSignalName_LowLevelSalonLiquid, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_ReadyForUseLC{"ReadyForUseLC",MAX_LENGTH_NAME};
static CanSignal ReadyForUseLC{ 24, 2, gSignalName_ReadyForUseLC, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DLCC1_arraySignals[DLCC1_NumberOfSignals] = {&EngineAmberWarningLC, &EngineCoolantLevelLowLC, &EngineCoolantTempHighLC, &EngineRedStopLC, &LowLevelSalonLiquid, &ReadyForUseLC};
const messageNameCharStruct gMessageName_DLCC1{"DLCC1",MAX_LENGTH_NAME};
static CanMessageRx DLCC1(gMessageName_DLCC1, DLCC1_arraySignals, DLCC1_NumberOfSignals, 0x18FD075B, 8, 1000);

const uint8_t DLCC2_NumberOfSignals = 6;
const signalNameCharStruct gSignalName_Optional1LC{"Optional1LC",MAX_LENGTH_NAME};
static CanSignal Optional1LC{ 18, 2, gSignalName_Optional1LC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Optional2LC{"Optional2LC",MAX_LENGTH_NAME};
static CanSignal Optional2LC{ 20, 2, gSignalName_Optional2LC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Optional3LC{"Optional3LC",MAX_LENGTH_NAME};
static CanSignal Optional3LC{ 22, 2, gSignalName_Optional3LC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Optional4LC{"Optional4LC",MAX_LENGTH_NAME};
static CanSignal Optional4LC{ 24, 2, gSignalName_Optional4LC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_VehicleBatteryChargingLC{"VehicleBatteryChargingLC",MAX_LENGTH_NAME};
static CanSignal VehicleBatteryChargingLC{ 8, 2, gSignalName_VehicleBatteryChargingLC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_VehicleLimitedPerformanceModeLC{"VehicleLimitedPerformanceModeLC",MAX_LENGTH_NAME};
static CanSignal VehicleLimitedPerformanceModeLC{ 12, 2, gSignalName_VehicleLimitedPerformanceModeLC, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DLCC2_arraySignals[DLCC2_NumberOfSignals] = {&Optional1LC, &Optional2LC, &Optional3LC, &Optional4LC, &VehicleBatteryChargingLC, &VehicleLimitedPerformanceModeLC};
const messageNameCharStruct gMessageName_DLCC2{"DLCC2",MAX_LENGTH_NAME};
static CanMessageRx DLCC2(gMessageName_DLCC2, DLCC2_arraySignals, DLCC2_NumberOfSignals, 0x18FD065B, 8, 1000);

const uint8_t DLDC1_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_LowLevel_CL{"LowLevel_CL",MAX_LENGTH_NAME};
static CanSignal LowLevel_CL{ 16, 2, gSignalName_LowLevel_CL, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DLDC1_arraySignals[DLDC1_NumberOfSignals] = {&LowLevel_CL};
const messageNameCharStruct gMessageName_DLDC1{"DLDC1",MAX_LENGTH_NAME};
static CanMessageRx DLDC1(gMessageName_DLDC1, DLDC1_arraySignals, DLDC1_NumberOfSignals, 0x18FD055B, 8, 100);

const uint8_t DM1_EBS_NumberOfSignals = 9;
const signalNameCharStruct gSignalName_EBS_DM_AmberLamp{"EBS_DM_AmberLamp",MAX_LENGTH_NAME};
static CanSignal EBS_DM_AmberLamp{ 2, 2, gSignalName_EBS_DM_AmberLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EBS_DM_CM{"EBS_DM_CM",MAX_LENGTH_NAME};
static CanSignal EBS_DM_CM{ 47, 1, gSignalName_EBS_DM_CM, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EBS_DM_FMI{"EBS_DM_FMI",MAX_LENGTH_NAME};
static CanSignal EBS_DM_FMI{ 32, 5, gSignalName_EBS_DM_FMI, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EBS_DM_Mailfunction{"EBS_DM_Mailfunction",MAX_LENGTH_NAME};
static CanSignal EBS_DM_Mailfunction{ 6, 2, gSignalName_EBS_DM_Mailfunction, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EBS_DM_OC{"EBS_DM_OC",MAX_LENGTH_NAME};
static CanSignal EBS_DM_OC{ 40, 7, gSignalName_EBS_DM_OC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EBS_DM_ProtectLamp{"EBS_DM_ProtectLamp",MAX_LENGTH_NAME};
static CanSignal EBS_DM_ProtectLamp{ 0, 2, gSignalName_EBS_DM_ProtectLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EBS_DM_RedLamp{"EBS_DM_RedLamp",MAX_LENGTH_NAME};
static CanSignal EBS_DM_RedLamp{ 4, 2, gSignalName_EBS_DM_RedLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EBS_DM_SPN1{"EBS_DM_SPN1",MAX_LENGTH_NAME};
static CanSignal EBS_DM_SPN1{ 16, 16, gSignalName_EBS_DM_SPN1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EBS_DM_SPN2{"EBS_DM_SPN2",MAX_LENGTH_NAME};
static CanSignal EBS_DM_SPN2{ 37, 3, gSignalName_EBS_DM_SPN2, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DM1_EBS_arraySignals[DM1_EBS_NumberOfSignals] = {&EBS_DM_AmberLamp, &EBS_DM_CM, &EBS_DM_FMI, &EBS_DM_Mailfunction, &EBS_DM_OC, &EBS_DM_ProtectLamp, &EBS_DM_RedLamp, &EBS_DM_SPN1, &EBS_DM_SPN2};
const messageNameCharStruct gMessageName_DM1_EBS{"DM1_EBS",MAX_LENGTH_NAME};
static CanMessageRx DM1_EBS(gMessageName_DM1_EBS, DM1_EBS_arraySignals, DM1_EBS_NumberOfSignals, 0x18FECA0B, 8, 1000);

const uint8_t DM1_EPB_NumberOfSignals = 9;
const signalNameCharStruct gSignalName_EPB_DM_AmberLamp{"EPB_DM_AmberLamp",MAX_LENGTH_NAME};
static CanSignal EPB_DM_AmberLamp{ 2, 2, gSignalName_EPB_DM_AmberLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EPB_DM_CM{"EPB_DM_CM",MAX_LENGTH_NAME};
static CanSignal EPB_DM_CM{ 47, 1, gSignalName_EPB_DM_CM, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EPB_DM_FMI{"EPB_DM_FMI",MAX_LENGTH_NAME};
static CanSignal EPB_DM_FMI{ 32, 5, gSignalName_EPB_DM_FMI, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EPB_DM_Mailfunction{"EPB_DM_Mailfunction",MAX_LENGTH_NAME};
static CanSignal EPB_DM_Mailfunction{ 6, 2, gSignalName_EPB_DM_Mailfunction, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EPB_DM_OC{"EPB_DM_OC",MAX_LENGTH_NAME};
static CanSignal EPB_DM_OC{ 40, 7, gSignalName_EPB_DM_OC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EPB_DM_ProtectLamp{"EPB_DM_ProtectLamp",MAX_LENGTH_NAME};
static CanSignal EPB_DM_ProtectLamp{ 0, 2, gSignalName_EPB_DM_ProtectLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EPB_DM_RedLamp{"EPB_DM_RedLamp",MAX_LENGTH_NAME};
static CanSignal EPB_DM_RedLamp{ 4, 2, gSignalName_EPB_DM_RedLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EPB_DM_SPN1{"EPB_DM_SPN1",MAX_LENGTH_NAME};
static CanSignal EPB_DM_SPN1{ 16, 16, gSignalName_EPB_DM_SPN1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EPB_DM_SPN2{"EPB_DM_SPN2",MAX_LENGTH_NAME};
static CanSignal EPB_DM_SPN2{ 37, 3, gSignalName_EPB_DM_SPN2, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DM1_EPB_arraySignals[DM1_EPB_NumberOfSignals] = {&EPB_DM_AmberLamp, &EPB_DM_CM, &EPB_DM_FMI, &EPB_DM_Mailfunction, &EPB_DM_OC, &EPB_DM_ProtectLamp, &EPB_DM_RedLamp, &EPB_DM_SPN1, &EPB_DM_SPN2};
const messageNameCharStruct gMessageName_DM1_EPB{"DM1_EPB",MAX_LENGTH_NAME};
static CanMessageRx DM1_EPB(gMessageName_DM1_EPB, DM1_EPB_arraySignals, DM1_EPB_NumberOfSignals, 0x18FECA50, 8, 1000);

const uint8_t DM1_Suspension_NumberOfSignals = 9;
const signalNameCharStruct gSignalName_susDM_AmberLamp{"susDM_AmberLamp",MAX_LENGTH_NAME};
static CanSignal susDM_AmberLamp{ 2, 2, gSignalName_susDM_AmberLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_susDM_CM{"susDM_CM",MAX_LENGTH_NAME};
static CanSignal susDM_CM{ 47, 1, gSignalName_susDM_CM, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_susDM_FMI{"susDM_FMI",MAX_LENGTH_NAME};
static CanSignal susDM_FMI{ 32, 5, gSignalName_susDM_FMI, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_susDM_Mailfunction{"susDM_Mailfunction",MAX_LENGTH_NAME};
static CanSignal susDM_Mailfunction{ 6, 2, gSignalName_susDM_Mailfunction, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_susDM_OC{"susDM_OC",MAX_LENGTH_NAME};
static CanSignal susDM_OC{ 40, 7, gSignalName_susDM_OC, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_susDM_ProtectLamp{"susDM_ProtectLamp",MAX_LENGTH_NAME};
static CanSignal susDM_ProtectLamp{ 0, 2, gSignalName_susDM_ProtectLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_susDM_RedLamp{"susDM_RedLamp",MAX_LENGTH_NAME};
static CanSignal susDM_RedLamp{ 4, 2, gSignalName_susDM_RedLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_susDM_SPN1{"susDM_SPN1",MAX_LENGTH_NAME};
static CanSignal susDM_SPN1{ 16, 16, gSignalName_susDM_SPN1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_susDM_SPN2{"susDM_SPN2",MAX_LENGTH_NAME};
static CanSignal susDM_SPN2{ 37, 3, gSignalName_susDM_SPN2, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DM1_Suspension_arraySignals[DM1_Suspension_NumberOfSignals] = {&susDM_AmberLamp, &susDM_CM, &susDM_FMI, &susDM_Mailfunction, &susDM_OC, &susDM_ProtectLamp, &susDM_RedLamp, &susDM_SPN1, &susDM_SPN2};
const messageNameCharStruct gMessageName_DM1_Suspension{"DM1_Suspension",MAX_LENGTH_NAME};
static CanMessageRx DM1_Suspension(gMessageName_DM1_Suspension, DM1_Suspension_arraySignals, DM1_Suspension_NumberOfSignals, 0x18FECA2F, 8, 0);

const uint8_t DOZC_1_NumberOfSignals = 15;
const signalNameCharStruct gSignalName_Door1CapInside{"Door1CapInside",MAX_LENGTH_NAME};
static CanSignal Door1CapInside{ 50, 2, gSignalName_Door1CapInside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1CapOutside{"Door1CapOutside",MAX_LENGTH_NAME};
static CanSignal Door1CapOutside{ 54, 2, gSignalName_Door1CapOutside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1Close{"Door1Close",MAX_LENGTH_NAME};
static CanSignal Door1Close{ 30, 2, gSignalName_Door1Close, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1Closing{"Door1Closing",MAX_LENGTH_NAME};
static CanSignal Door1Closing{ 26, 2, gSignalName_Door1Closing, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1EmgOpening{"Door1EmgOpening",MAX_LENGTH_NAME};
static CanSignal Door1EmgOpening{ 18, 2, gSignalName_Door1EmgOpening, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1Open{"Door1Open",MAX_LENGTH_NAME};
static CanSignal Door1Open{ 20, 2, gSignalName_Door1Open, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1Opening{"Door1Opening",MAX_LENGTH_NAME};
static CanSignal Door1Opening{ 28, 2, gSignalName_Door1Opening, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1Pinching1{"Door1Pinching1",MAX_LENGTH_NAME};
static CanSignal Door1Pinching1{ 6, 2, gSignalName_Door1Pinching1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1Pinching2{"Door1Pinching2",MAX_LENGTH_NAME};
static CanSignal Door1Pinching2{ 8, 2, gSignalName_Door1Pinching2, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1Pinching3{"Door1Pinching3",MAX_LENGTH_NAME};
static CanSignal Door1Pinching3{ 10, 2, gSignalName_Door1Pinching3, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1RampOpen{"Door1RampOpen",MAX_LENGTH_NAME};
static CanSignal Door1RampOpen{ 58, 2, gSignalName_Door1RampOpen, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1RqOpenInside{"Door1RqOpenInside",MAX_LENGTH_NAME};
static CanSignal Door1RqOpenInside{ 14, 2, gSignalName_Door1RqOpenInside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1RqOpenOutside{"Door1RqOpenOutside",MAX_LENGTH_NAME};
static CanSignal Door1RqOpenOutside{ 12, 2, gSignalName_Door1RqOpenOutside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1ValveInside{"Door1ValveInside",MAX_LENGTH_NAME};
static CanSignal Door1ValveInside{ 52, 2, gSignalName_Door1ValveInside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door1ValveOutside{"Door1ValveOutside",MAX_LENGTH_NAME};
static CanSignal Door1ValveOutside{ 56, 2, gSignalName_Door1ValveOutside, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DOZC_1_arraySignals[DOZC_1_NumberOfSignals] = {&Door1CapInside, &Door1CapOutside, &Door1Close, &Door1Closing, &Door1EmgOpening, &Door1Open, &Door1Opening, &Door1Pinching1, &Door1Pinching2, &Door1Pinching3, &Door1RampOpen, &Door1RqOpenInside, &Door1RqOpenOutside, &Door1ValveInside, &Door1ValveOutside};
const messageNameCharStruct gMessageName_DOZC_1{"DOZC_1",MAX_LENGTH_NAME};
static CanMessageRx DOZC_1(gMessageName_DOZC_1, DOZC_1_arraySignals, DOZC_1_NumberOfSignals, 0x18FD1ECC, 8, 100);

const uint8_t DOZC_2_NumberOfSignals = 15;
const signalNameCharStruct gSignalName_Door2CapInside{"Door2CapInside",MAX_LENGTH_NAME};
static CanSignal Door2CapInside{ 50, 2, gSignalName_Door2CapInside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2CapOutside{"Door2CapOutside",MAX_LENGTH_NAME};
static CanSignal Door2CapOutside{ 54, 2, gSignalName_Door2CapOutside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2Close{"Door2Close",MAX_LENGTH_NAME};
static CanSignal Door2Close{ 30, 2, gSignalName_Door2Close, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2Closing{"Door2Closing",MAX_LENGTH_NAME};
static CanSignal Door2Closing{ 26, 2, gSignalName_Door2Closing, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2EmgOpening{"Door2EmgOpening",MAX_LENGTH_NAME};
static CanSignal Door2EmgOpening{ 18, 2, gSignalName_Door2EmgOpening, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2Open{"Door2Open",MAX_LENGTH_NAME};
static CanSignal Door2Open{ 20, 2, gSignalName_Door2Open, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2Opening{"Door2Opening",MAX_LENGTH_NAME};
static CanSignal Door2Opening{ 28, 2, gSignalName_Door2Opening, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2Pinching1{"Door2Pinching1",MAX_LENGTH_NAME};
static CanSignal Door2Pinching1{ 6, 2, gSignalName_Door2Pinching1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2Pinching2{"Door2Pinching2",MAX_LENGTH_NAME};
static CanSignal Door2Pinching2{ 8, 2, gSignalName_Door2Pinching2, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2Pinching3{"Door2Pinching3",MAX_LENGTH_NAME};
static CanSignal Door2Pinching3{ 10, 2, gSignalName_Door2Pinching3, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2RampOpen{"Door2RampOpen",MAX_LENGTH_NAME};
static CanSignal Door2RampOpen{ 58, 2, gSignalName_Door2RampOpen, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2RqOpenInside{"Door2RqOpenInside",MAX_LENGTH_NAME};
static CanSignal Door2RqOpenInside{ 14, 2, gSignalName_Door2RqOpenInside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2RqOpenOutside{"Door2RqOpenOutside",MAX_LENGTH_NAME};
static CanSignal Door2RqOpenOutside{ 12, 2, gSignalName_Door2RqOpenOutside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2ValveInside{"Door2ValveInside",MAX_LENGTH_NAME};
static CanSignal Door2ValveInside{ 52, 2, gSignalName_Door2ValveInside, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Door2ValveOutside{"Door2ValveOutside",MAX_LENGTH_NAME};
static CanSignal Door2ValveOutside{ 56, 2, gSignalName_Door2ValveOutside, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DOZC_2_arraySignals[DOZC_2_NumberOfSignals] = {&Door2CapInside, &Door2CapOutside, &Door2Close, &Door2Closing, &Door2EmgOpening, &Door2Open, &Door2Opening, &Door2Pinching1, &Door2Pinching2, &Door2Pinching3, &Door2RampOpen, &Door2RqOpenInside, &Door2RqOpenOutside, &Door2ValveInside, &Door2ValveOutside};
const messageNameCharStruct gMessageName_DOZC_2{"DOZC_2",MAX_LENGTH_NAME};
static CanMessageRx DOZC_2(gMessageName_DOZC_2, DOZC_2_arraySignals, DOZC_2_NumberOfSignals, 0x18FD1ECD, 8, 100);

const uint8_t EBC1_NumberOfSignals = 10;
const signalNameCharStruct gSignalName_ABS_Active{"ABS_Active",MAX_LENGTH_NAME};
static CanSignal ABS_Active{ 4, 2, gSignalName_ABS_Active, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_ABS_FullyOpeartinal{"ABS_FullyOpeartinal",MAX_LENGTH_NAME};
static CanSignal ABS_FullyOpeartinal{ 40, 2, gSignalName_ABS_FullyOpeartinal, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_ASR_BrakeControlActive{"ASR_BrakeControlActive",MAX_LENGTH_NAME};
static CanSignal ASR_BrakeControlActive{ 2, 2, gSignalName_ASR_BrakeControlActive, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_ASR_EngineControlActive{"ASR_EngineControlActive",MAX_LENGTH_NAME};
static CanSignal ASR_EngineControlActive{ 0, 2, gSignalName_ASR_EngineControlActive, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_ASR_HillHolderSwitch{"ASR_HillHolderSwitch",MAX_LENGTH_NAME};
static CanSignal ASR_HillHolderSwitch{ 20, 2, gSignalName_ASR_HillHolderSwitch, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_ASR_OffRoadSwitch{"ASR_OffRoadSwitch",MAX_LENGTH_NAME};
static CanSignal ASR_OffRoadSwitch{ 18, 2, gSignalName_ASR_OffRoadSwitch, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_ASR_infoSignal{"ASR_infoSignal",MAX_LENGTH_NAME};
static CanSignal ASR_infoSignal{ 46, 2, gSignalName_ASR_infoSignal, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EBS_RedLamp{"EBS_RedLamp",MAX_LENGTH_NAME};
static CanSignal EBS_RedLamp{ 42, 2, gSignalName_EBS_RedLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_EBS_WarningLamp{"EBS_WarningLamp",MAX_LENGTH_NAME};
static CanSignal EBS_WarningLamp{ 44, 2, gSignalName_EBS_WarningLamp, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_TractionControlOverrideSwitch{"TractionControlOverrideSwitch",MAX_LENGTH_NAME};
static CanSignal TractionControlOverrideSwitch{ 22, 2, gSignalName_TractionControlOverrideSwitch, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *EBC1_arraySignals[EBC1_NumberOfSignals] = {&ABS_Active, &ABS_FullyOpeartinal, &ASR_BrakeControlActive, &ASR_EngineControlActive, &ASR_HillHolderSwitch, &ASR_OffRoadSwitch, &ASR_infoSignal, &EBS_RedLamp, &EBS_WarningLamp, &TractionControlOverrideSwitch};
const messageNameCharStruct gMessageName_EBC1{"EBC1",MAX_LENGTH_NAME};
static CanMessageRx EBC1(gMessageName_EBC1, EBC1_arraySignals, EBC1_NumberOfSignals, 0x18F0010B, 8, 100);

const uint8_t EBC4_NumberOfSignals = 8;
const signalNameCharStruct gSignalName_FrontAxleLeft{"FrontAxleLeft",MAX_LENGTH_NAME};
static CanSignal FrontAxleLeft{ 0, 8, gSignalName_FrontAxleLeft, 0.4, 0, canIntel, canUint, 100, 0, 0};
const signalNameCharStruct gSignalName_FrontAxleRight{"FrontAxleRight",MAX_LENGTH_NAME};
static CanSignal FrontAxleRight{ 8, 8, gSignalName_FrontAxleRight, 0.4, 0, canIntel, canUint, 100, 0, 0};
const signalNameCharStruct gSignalName_RearAxle1LeftWheel{"RearAxle1LeftWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle1LeftWheel{ 16, 8, gSignalName_RearAxle1LeftWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
const signalNameCharStruct gSignalName_RearAxle1RightWheel{"RearAxle1RightWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle1RightWheel{ 24, 8, gSignalName_RearAxle1RightWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
const signalNameCharStruct gSignalName_RearAxle2LeftWheel{"RearAxle2LeftWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle2LeftWheel{ 32, 8, gSignalName_RearAxle2LeftWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
const signalNameCharStruct gSignalName_RearAxle2RightWheel{"RearAxle2RightWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle2RightWheel{ 40, 8, gSignalName_RearAxle2RightWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
const signalNameCharStruct gSignalName_RearAxle3LeftWheel{"RearAxle3LeftWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle3LeftWheel{ 48, 8, gSignalName_RearAxle3LeftWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
const signalNameCharStruct gSignalName_RearAxle3RightWheel{"RearAxle3RightWheel",MAX_LENGTH_NAME};
static CanSignal RearAxle3RightWheel{ 56, 8, gSignalName_RearAxle3RightWheel, 0.4, 0, canIntel, canUint, 100, 0, 0};
static CanSignal *EBC4_arraySignals[EBC4_NumberOfSignals] = {&FrontAxleLeft, &FrontAxleRight, &RearAxle1LeftWheel, &RearAxle1RightWheel, &RearAxle2LeftWheel, &RearAxle2RightWheel, &RearAxle3LeftWheel, &RearAxle3RightWheel};
const messageNameCharStruct gMessageName_EBC4{"EBC4",MAX_LENGTH_NAME};
static CanMessageRx EBC4(gMessageName_EBC4, EBC4_arraySignals, EBC4_NumberOfSignals, 0x1CFEAC0B, 8, 100);

const uint8_t EBC5_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_HaltBrakeMode{"HaltBrakeMode",MAX_LENGTH_NAME};
static CanSignal HaltBrakeMode{ 2, 3, gSignalName_HaltBrakeMode, 1, 0, canIntel, canUint, 7, 0, 0};
const signalNameCharStruct gSignalName_HillHolderMode{"HillHolderMode",MAX_LENGTH_NAME};
static CanSignal HillHolderMode{ 5, 3, gSignalName_HillHolderMode, 1, 0, canIntel, canUint, 7, 0, 0};
static CanSignal *EBC5_arraySignals[EBC5_NumberOfSignals] = {&HaltBrakeMode, &HillHolderMode};
const messageNameCharStruct gMessageName_EBC5{"EBC5",MAX_LENGTH_NAME};
static CanMessageRx EBC5(gMessageName_EBC5, EBC5_arraySignals, EBC5_NumberOfSignals, 0x18FDC40B, 8, 100);

const uint8_t ECO_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_Eco_s{"Eco_s",MAX_LENGTH_NAME};
static CanSignal Eco_s{ 52, 2, gSignalName_Eco_s, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ECO_arraySignals[ECO_NumberOfSignals] = {&Eco_s};
const messageNameCharStruct gMessageName_ECO{"ECO",MAX_LENGTH_NAME};
static CanMessageRx ECO(gMessageName_ECO, ECO_arraySignals, ECO_NumberOfSignals, 0x18FF083A, 8, 100);

const uint8_t EDSC2_2_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_RequestOpenRamp1{"RequestOpenRamp1",MAX_LENGTH_NAME};
static CanSignal RequestOpenRamp1{ 4, 2, gSignalName_RequestOpenRamp1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_RequestOpenRamp2{"RequestOpenRamp2",MAX_LENGTH_NAME};
static CanSignal RequestOpenRamp2{ 6, 2, gSignalName_RequestOpenRamp2, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *EDSC2_2_arraySignals[EDSC2_2_NumberOfSignals] = {&RequestOpenRamp1, &RequestOpenRamp2};
const messageNameCharStruct gMessageName_EDSC2_2{"EDSC2_2",MAX_LENGTH_NAME};
static CanMessageRx EDSC2_2(gMessageName_EDSC2_2, EDSC2_2_arraySignals, EDSC2_2_NumberOfSignals, 0x18FFBDCD, 8, 100);

const uint8_t EPBS1_NumberOfSignals = 3;
const signalNameCharStruct gSignalName_ElectricParkingBrake{"ElectricParkingBrake",MAX_LENGTH_NAME};
static CanSignal ElectricParkingBrake{ 0, 2, gSignalName_ElectricParkingBrake, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_ParkingWorkStatus1{"ParkingWorkStatus1",MAX_LENGTH_NAME};
static CanSignal ParkingWorkStatus1{ 2, 2, gSignalName_ParkingWorkStatus1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_ParkingWorkStatus2{"ParkingWorkStatus2",MAX_LENGTH_NAME};
static CanSignal ParkingWorkStatus2{ 4, 2, gSignalName_ParkingWorkStatus2, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *EPBS1_arraySignals[EPBS1_NumberOfSignals] = {&ElectricParkingBrake, &ParkingWorkStatus1, &ParkingWorkStatus2};
const messageNameCharStruct gMessageName_EPBS1{"EPBS1",MAX_LENGTH_NAME};
static CanMessageRx EPBS1(gMessageName_EPBS1, EPBS1_arraySignals, EPBS1_NumberOfSignals, 0x18FE1250, 8, 100);

const uint8_t ESC2_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_WheelSteerActuatorState{"WheelSteerActuatorState",MAX_LENGTH_NAME};
static CanSignal WheelSteerActuatorState{ 8, 2, gSignalName_WheelSteerActuatorState, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ESC2_arraySignals[ESC2_NumberOfSignals] = {&WheelSteerActuatorState};
const messageNameCharStruct gMessageName_ESC2{"ESC2",MAX_LENGTH_NAME};
static CanMessageRx ESC2(gMessageName_ESC2, ESC2_arraySignals, ESC2_NumberOfSignals, 0x18FC9713, 8, 500);

const uint8_t ET1_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_Temp_CL{"Temp_CL",MAX_LENGTH_NAME};
static CanSignal Temp_CL{ 0, 8, gSignalName_Temp_CL, 1, -40, canIntel, canUint, 210, 0, 0};
static CanSignal *ET1_arraySignals[ET1_NumberOfSignals] = {&Temp_CL};
const messageNameCharStruct gMessageName_ET1{"ET1",MAX_LENGTH_NAME};
static CanMessageRx ET1(gMessageName_ET1, ET1_arraySignals, ET1_NumberOfSignals, 0x18FEEE5B, 8, 1000);

const uint8_t ETC2_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_TransmissionCurrentGear{"TransmissionCurrentGear",MAX_LENGTH_NAME};
static CanSignal TransmissionCurrentGear{ 24, 8, gSignalName_TransmissionCurrentGear, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ETC2_arraySignals[ETC2_NumberOfSignals] = {&TransmissionCurrentGear};
const messageNameCharStruct gMessageName_ETC2{"ETC2",MAX_LENGTH_NAME};
static CanMessageRx ETC2(gMessageName_ETC2, ETC2_arraySignals, ETC2_NumberOfSignals, 0x18F0055B, 8, 100);

const uint8_t FS1_NumberOfSignals = 8;
const signalNameCharStruct gSignalName_EmergHammer_1{"EmergHammer_1",MAX_LENGTH_NAME};
static CanSignal EmergHammer_1{ 16, 2, gSignalName_EmergHammer_1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EmergHammer_2{"EmergHammer_2",MAX_LENGTH_NAME};
static CanSignal EmergHammer_2{ 18, 2, gSignalName_EmergHammer_2, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EmergHammer_3{"EmergHammer_3",MAX_LENGTH_NAME};
static CanSignal EmergHammer_3{ 20, 2, gSignalName_EmergHammer_3, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_EmergHammer_4{"EmergHammer_4",MAX_LENGTH_NAME};
static CanSignal EmergHammer_4{ 22, 2, gSignalName_EmergHammer_4, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_FireExting_1{"FireExting_1",MAX_LENGTH_NAME};
static CanSignal FireExting_1{ 0, 2, gSignalName_FireExting_1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_FireExting_2{"FireExting_2",MAX_LENGTH_NAME};
static CanSignal FireExting_2{ 2, 2, gSignalName_FireExting_2, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_FireExting_3{"FireExting_3",MAX_LENGTH_NAME};
static CanSignal FireExting_3{ 4, 2, gSignalName_FireExting_3, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_FireExting_4{"FireExting_4",MAX_LENGTH_NAME};
static CanSignal FireExting_4{ 6, 2, gSignalName_FireExting_4, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *FS1_arraySignals[FS1_NumberOfSignals] = {&EmergHammer_1, &EmergHammer_2, &EmergHammer_3, &EmergHammer_4, &FireExting_1, &FireExting_2, &FireExting_3, &FireExting_4};
const messageNameCharStruct gMessageName_FS1{"FS1",MAX_LENGTH_NAME};
static CanMessageRx FS1(gMessageName_FS1, FS1_arraySignals, FS1_NumberOfSignals, 0x18FF505D, 8, 200);

const uint8_t HVESSD1_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_HVESS_Current{"HVESS_Current",MAX_LENGTH_NAME};
static CanSignal HVESS_Current{ 48, 16, gSignalName_HVESS_Current, 0.05, -1600, canIntel, canUint, 1612.75, -1600, 0};
const signalNameCharStruct gSignalName_HVESS_VoltageLevel{"HVESS_VoltageLevel",MAX_LENGTH_NAME};
static CanSignal HVESS_VoltageLevel{ 32, 16, gSignalName_HVESS_VoltageLevel, 0.05, 0, canIntel, canUint, 3212.75, 0, 0};
static CanSignal *HVESSD1_arraySignals[HVESSD1_NumberOfSignals] = {&HVESS_Current, &HVESS_VoltageLevel};
const messageNameCharStruct gMessageName_HVESSD1{"HVESSD1",MAX_LENGTH_NAME};
static CanMessageRx HVESSD1(gMessageName_HVESSD1, HVESSD1_arraySignals, HVESSD1_NumberOfSignals, 0x0CF090F3, 8, 20);

const uint8_t HVESSD2_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_HVESS_FastUpdateSoc{"HVESS_FastUpdateSoc",MAX_LENGTH_NAME};
static CanSignal HVESS_FastUpdateSoc{ 0, 16, gSignalName_HVESS_FastUpdateSoc, 0.0015625, 0, canIntel, canUint, 100, 0, 0};
static CanSignal *HVESSD2_arraySignals[HVESSD2_NumberOfSignals] = {&HVESS_FastUpdateSoc};
const messageNameCharStruct gMessageName_HVESSD2{"HVESSD2",MAX_LENGTH_NAME};
static CanMessageRx HVESSD2(gMessageName_HVESSD2, HVESSD2_arraySignals, HVESSD2_NumberOfSignals, 0x0CF091F3, 8, 20);

const uint8_t HVESSD3_NumberOfSignals = 3;
const signalNameCharStruct gSignalName_AverageCellTemp{"AverageCellTemp",MAX_LENGTH_NAME};
static CanSignal AverageCellTemp{ 32, 16, gSignalName_AverageCellTemp, 0.03125, -273, canIntel, canUint, 2000, -273, 0};
const signalNameCharStruct gSignalName_HighestCellTemp{"HighestCellTemp",MAX_LENGTH_NAME};
static CanSignal HighestCellTemp{ 0, 16, gSignalName_HighestCellTemp, 0.03125, -273, canIntel, canUint, 2000, -273, 0};
const signalNameCharStruct gSignalName_LowestCellTemp{"LowestCellTemp",MAX_LENGTH_NAME};
static CanSignal LowestCellTemp{ 16, 16, gSignalName_LowestCellTemp, 0.03125, -273, canIntel, canUint, 2000, -273, 0};
static CanSignal *HVESSD3_arraySignals[HVESSD3_NumberOfSignals] = {&AverageCellTemp, &HighestCellTemp, &LowestCellTemp};
const messageNameCharStruct gMessageName_HVESSD3{"HVESSD3",MAX_LENGTH_NAME};
static CanMessageRx HVESSD3(gMessageName_HVESSD3, HVESSD3_arraySignals, HVESSD3_NumberOfSignals, 0x0CF092F3, 8, 1000);

const uint8_t HVESSD5_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_ChargeCurrentLimit{"ChargeCurrentLimit",MAX_LENGTH_NAME};
static CanSignal ChargeCurrentLimit{ 16, 16, gSignalName_ChargeCurrentLimit, 0.05, 0, canIntel, canUint, 1600, -1600, 0};
const signalNameCharStruct gSignalName_DischargeCurrentLimit{"DischargeCurrentLimit",MAX_LENGTH_NAME};
static CanSignal DischargeCurrentLimit{ 0, 16, gSignalName_DischargeCurrentLimit, 0.05, 0, canIntel, canUint, 1600, -1600, 0};
static CanSignal *HVESSD5_arraySignals[HVESSD5_NumberOfSignals] = {&ChargeCurrentLimit, &DischargeCurrentLimit};
const messageNameCharStruct gMessageName_HVESSD5{"HVESSD5",MAX_LENGTH_NAME};
static CanMessageRx HVESSD5(gMessageName_HVESSD5, HVESSD5_arraySignals, HVESSD5_NumberOfSignals, 0x0CF094F3, 8, 100);

const uint8_t HVESSD6_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_ElectronicTemp{"ElectronicTemp",MAX_LENGTH_NAME};
static CanSignal ElectronicTemp{ 48, 8, gSignalName_ElectronicTemp, 1, -40, canIntel, canUint, 250, -40, 0};
static CanSignal *HVESSD6_arraySignals[HVESSD6_NumberOfSignals] = {&ElectronicTemp};
const messageNameCharStruct gMessageName_HVESSD6{"HVESSD6",MAX_LENGTH_NAME};
static CanMessageRx HVESSD6(gMessageName_HVESSD6, HVESSD6_arraySignals, HVESSD6_NumberOfSignals, 0x0CF095F3, 8, 1000);

const uint8_t HVESSS1_NumberOfSignals = 5;
const signalNameCharStruct gSignalName_HVESS_CenterOfPackContactor{"HVESS_CenterOfPackContactor",MAX_LENGTH_NAME};
static CanSignal HVESS_CenterOfPackContactor{ 10, 2, gSignalName_HVESS_CenterOfPackContactor, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_HVESS_HvBusConnectionStatus{"HVESS_HvBusConnectionStatus",MAX_LENGTH_NAME};
static CanSignal HVESS_HvBusConnectionStatus{ 40, 4, gSignalName_HVESS_HvBusConnectionStatus, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_HVESS_HvBusPrechargeRelay{"HVESS_HvBusPrechargeRelay",MAX_LENGTH_NAME};
static CanSignal HVESS_HvBusPrechargeRelay{ 8, 2, gSignalName_HVESS_HvBusPrechargeRelay, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_HVESS_HvNegativeContactorState{"HVESS_HvNegativeContactorState",MAX_LENGTH_NAME};
static CanSignal HVESS_HvNegativeContactorState{ 2, 2, gSignalName_HVESS_HvNegativeContactorState, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_HVESS_HvPositiveContactorState{"HVESS_HvPositiveContactorState",MAX_LENGTH_NAME};
static CanSignal HVESS_HvPositiveContactorState{ 0, 2, gSignalName_HVESS_HvPositiveContactorState, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *HVESSS1_arraySignals[HVESSS1_NumberOfSignals] = {&HVESS_CenterOfPackContactor, &HVESS_HvBusConnectionStatus, &HVESS_HvBusPrechargeRelay, &HVESS_HvNegativeContactorState, &HVESS_HvPositiveContactorState};
const messageNameCharStruct gMessageName_HVESSS1{"HVESSS1",MAX_LENGTH_NAME};
static CanMessageRx HVESSS1(gMessageName_HVESSS1, HVESSS1_arraySignals, HVESSS1_NumberOfSignals, 0x0CF096F3, 8, 100);

const uint8_t ISOTP_PC_ID_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_IsoTpDataPC{"IsoTpDataPC",MAX_LENGTH_NAME};
static CanSignal IsoTpDataPC{ 0, 64, gSignalName_IsoTpDataPC, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ISOTP_PC_ID_arraySignals[ISOTP_PC_ID_NumberOfSignals] = {&IsoTpDataPC};
const messageNameCharStruct gMessageName_ISOTP_PC_ID{"ISOTP_PC_ID",MAX_LENGTH_NAME};
static CanMessageRx ISOTP_PC_ID(gMessageName_ISOTP_PC_ID, ISOTP_PC_ID_arraySignals, ISOTP_PC_ID_NumberOfSignals, 0x00FF04FD, 8, 0);

const uint8_t LD_NumberOfSignals = 9;
const signalNameCharStruct gSignalName_FrontFogLight{"FrontFogLight",MAX_LENGTH_NAME};
static CanSignal FrontFogLight{ 8, 2, gSignalName_FrontFogLight, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_HighBeamHeadLight{"HighBeamHeadLight",MAX_LENGTH_NAME};
static CanSignal HighBeamHeadLight{ 6, 2, gSignalName_HighBeamHeadLight, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_ImplementOEMOption1Light{"ImplementOEMOption1Light",MAX_LENGTH_NAME};
static CanSignal ImplementOEMOption1Light{ 50, 2, gSignalName_ImplementOEMOption1Light, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_LeftTurnSignalLight{"LeftTurnSignalLight",MAX_LENGTH_NAME};
static CanSignal LeftTurnSignalLight{ 14, 2, gSignalName_LeftTurnSignalLight, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_LowBeamHeadLight{"LowBeamHeadLight",MAX_LENGTH_NAME};
static CanSignal LowBeamHeadLight{ 4, 2, gSignalName_LowBeamHeadLight, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_MarkerLight{"MarkerLight",MAX_LENGTH_NAME};
static CanSignal MarkerLight{ 30, 2, gSignalName_MarkerLight, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_RearFogLight{"RearFogLight",MAX_LENGTH_NAME};
static CanSignal RearFogLight{ 32, 2, gSignalName_RearFogLight, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_RightTurnSignalLight{"RightTurnSignalLight",MAX_LENGTH_NAME};
static CanSignal RightTurnSignalLight{ 12, 2, gSignalName_RightTurnSignalLight, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_RunningLight{"RunningLight",MAX_LENGTH_NAME};
static CanSignal RunningLight{ 0, 2, gSignalName_RunningLight, 1, 0, canIntel, canUint, 3, 0, 0};
static CanSignal *LD_arraySignals[LD_NumberOfSignals] = {&FrontFogLight, &HighBeamHeadLight, &ImplementOEMOption1Light, &LeftTurnSignalLight, &LowBeamHeadLight, &MarkerLight, &RearFogLight, &RightTurnSignalLight, &RunningLight};
const messageNameCharStruct gMessageName_LD{"LD",MAX_LENGTH_NAME};
static CanMessageRx LD(gMessageName_LD, LD_arraySignals, LD_NumberOfSignals, 0x18FE401E, 8, 500);

const uint8_t LD_2_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_LowBeamLightAuto{"LowBeamLightAuto",MAX_LENGTH_NAME};
static CanSignal LowBeamLightAuto{ 4, 2, gSignalName_LowBeamLightAuto, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *LD_2_arraySignals[LD_2_NumberOfSignals] = {&LowBeamLightAuto};
const messageNameCharStruct gMessageName_LD_2{"LD_2",MAX_LENGTH_NAME};
static CanMessageRx LD_2(gMessageName_LD_2, LD_2_arraySignals, LD_2_NumberOfSignals, 0x0CFE4189, 8, 1000);

const uint8_t MCU2VCU2_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_ElectricEngineTemp{"ElectricEngineTemp",MAX_LENGTH_NAME};
static CanSignal ElectricEngineTemp{ 0, 8, gSignalName_ElectricEngineTemp, 1, -40, canIntel, canUint, 210, -40, 0};
static CanSignal *MCU2VCU2_arraySignals[MCU2VCU2_NumberOfSignals] = {&ElectricEngineTemp};
const messageNameCharStruct gMessageName_MCU2VCU2{"MCU2VCU2",MAX_LENGTH_NAME};
static CanMessageRx MCU2VCU2(gMessageName_MCU2VCU2, MCU2VCU2_arraySignals, MCU2VCU2_NumberOfSignals, 0x0CA4EFF0, 8, 1000);

const uint8_t OWW_NumberOfSignals = 3;
const signalNameCharStruct gSignalName_FrontNonOperatorWiperSwitch{"FrontNonOperatorWiperSwitch",MAX_LENGTH_NAME};
static CanSignal FrontNonOperatorWiperSwitch{ 0, 4, gSignalName_FrontNonOperatorWiperSwitch, 1, 0, canIntel, canUint, 15, 0, 0};
const signalNameCharStruct gSignalName_FrontOperatorWiperSwitch{"FrontOperatorWiperSwitch",MAX_LENGTH_NAME};
static CanSignal FrontOperatorWiperSwitch{ 4, 4, gSignalName_FrontOperatorWiperSwitch, 1, 0, canIntel, canUint, 15, 0, 0};
const signalNameCharStruct gSignalName_WindshieldWasherOn{"WindshieldWasherOn",MAX_LENGTH_NAME};
static CanSignal WindshieldWasherOn{ 45, 3, gSignalName_WindshieldWasherOn, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *OWW_arraySignals[OWW_NumberOfSignals] = {&FrontNonOperatorWiperSwitch, &FrontOperatorWiperSwitch, &WindshieldWasherOn};
const messageNameCharStruct gMessageName_OWW{"OWW",MAX_LENGTH_NAME};
static CanMessageRx OWW(gMessageName_OWW, OWW_arraySignals, OWW_NumberOfSignals, 0x18FDCD1E, 8, 200);

const uint8_t PCM1_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_PantographModuleState{"PantographModuleState",MAX_LENGTH_NAME};
static CanSignal PantographModuleState{ 0, 4, gSignalName_PantographModuleState, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *PCM1_arraySignals[PCM1_NumberOfSignals] = {&PantographModuleState};
const messageNameCharStruct gMessageName_PCM1{"PCM1",MAX_LENGTH_NAME};
static CanMessageRx PCM1(gMessageName_PCM1, PCM1_arraySignals, PCM1_NumberOfSignals, 0x18FF4F42, 8, 100);

const uint8_t SCU2CLM_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_HeatingWheel{"HeatingWheel",MAX_LENGTH_NAME};
static CanSignal HeatingWheel{ 6, 2, gSignalName_HeatingWheel, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *SCU2CLM_arraySignals[SCU2CLM_NumberOfSignals] = {&HeatingWheel};
const messageNameCharStruct gMessageName_SCU2CLM{"SCU2CLM",MAX_LENGTH_NAME};
static CanMessageRx SCU2CLM(gMessageName_SCU2CLM, SCU2CLM_arraySignals, SCU2CLM_NumberOfSignals, 0x18FF114D, 8, 50);

const uint8_t T2B_TMS1_NumberOfSignals = 4;
const signalNameCharStruct gSignalName_InletWaterTemp{"InletWaterTemp",MAX_LENGTH_NAME};
static CanSignal InletWaterTemp{ 0, 8, gSignalName_InletWaterTemp, 1, -40, canIntel, canUint, 250, -40, 0};
const signalNameCharStruct gSignalName_OutletWaterTemp{"OutletWaterTemp",MAX_LENGTH_NAME};
static CanSignal OutletWaterTemp{ 8, 8, gSignalName_OutletWaterTemp, 1, -40, canIntel, canUint, 250, -40, 0};
const signalNameCharStruct gSignalName_TMS_FaultCode{"TMS_FaultCode",MAX_LENGTH_NAME};
static CanSignal TMS_FaultCode{ 32, 6, gSignalName_TMS_FaultCode, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_TmsMode{"TmsMode",MAX_LENGTH_NAME};
static CanSignal TmsMode{ 17, 3, gSignalName_TmsMode, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *T2B_TMS1_arraySignals[T2B_TMS1_NumberOfSignals] = {&InletWaterTemp, &OutletWaterTemp, &TMS_FaultCode, &TmsMode};
const messageNameCharStruct gMessageName_T2B_TMS1{"T2B_TMS1",MAX_LENGTH_NAME};
static CanMessageRx T2B_TMS1(gMessageName_T2B_TMS1, T2B_TMS1_arraySignals, T2B_TMS1_NumberOfSignals, 0x18FFF345, 8, 1000);

const uint8_t TCO1_NumberOfSignals = 14;
const signalNameCharStruct gSignalName_DirectionIndicator{"DirectionIndicator",MAX_LENGTH_NAME};
static CanSignal DirectionIndicator{ 30, 2, gSignalName_DirectionIndicator, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_Driver1TimeRelatedStates{"Driver1TimeRelatedStates",MAX_LENGTH_NAME};
static CanSignal Driver1TimeRelatedStates{ 8, 4, gSignalName_Driver1TimeRelatedStates, 1, 0, canIntel, canUint, 15, 0, 0};
const signalNameCharStruct gSignalName_Driver1WorkingState{"Driver1WorkingState",MAX_LENGTH_NAME};
static CanSignal Driver1WorkingState{ 0, 3, gSignalName_Driver1WorkingState, 1, 0, canIntel, canUint, 7, 0, 0};
const signalNameCharStruct gSignalName_Driver2TimeRelatedStates{"Driver2TimeRelatedStates",MAX_LENGTH_NAME};
static CanSignal Driver2TimeRelatedStates{ 16, 4, gSignalName_Driver2TimeRelatedStates, 1, 0, canIntel, canUint, 15, 0, 0};
const signalNameCharStruct gSignalName_Driver2WorkingState{"Driver2WorkingState",MAX_LENGTH_NAME};
static CanSignal Driver2WorkingState{ 3, 3, gSignalName_Driver2WorkingState, 1, 0, canIntel, canUint, 7, 0, 0};
const signalNameCharStruct gSignalName_DriverCard_Driver1{"DriverCard_Driver1",MAX_LENGTH_NAME};
static CanSignal DriverCard_Driver1{ 12, 2, gSignalName_DriverCard_Driver1, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_DriverCard_Driver2{"DriverCard_Driver2",MAX_LENGTH_NAME};
static CanSignal DriverCard_Driver2{ 20, 2, gSignalName_DriverCard_Driver2, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_HandlingInformation{"HandlingInformation",MAX_LENGTH_NAME};
static CanSignal HandlingInformation{ 26, 2, gSignalName_HandlingInformation, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_SystemEvent{"SystemEvent",MAX_LENGTH_NAME};
static CanSignal SystemEvent{ 24, 2, gSignalName_SystemEvent, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_TachographOutputShaftSpeed{"TachographOutputShaftSpeed",MAX_LENGTH_NAME};
static CanSignal TachographOutputShaftSpeed{ 32, 16, gSignalName_TachographOutputShaftSpeed, 0.125, 0, canIntel, canUint, 8031.88, 0, 0};
const signalNameCharStruct gSignalName_TachographPerformance{"TachographPerformance",MAX_LENGTH_NAME};
static CanSignal TachographPerformance{ 28, 2, gSignalName_TachographPerformance, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_TachographVehicleSpeed{"TachographVehicleSpeed",MAX_LENGTH_NAME};
static CanSignal TachographVehicleSpeed{ 48, 16, gSignalName_TachographVehicleSpeed, 0.00390625, 0, canIntel, canUint, 250.996, 0, 0};
const signalNameCharStruct gSignalName_VehicleMotion{"VehicleMotion",MAX_LENGTH_NAME};
static CanSignal VehicleMotion{ 6, 2, gSignalName_VehicleMotion, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_VehicleOverspeed{"VehicleOverspeed",MAX_LENGTH_NAME};
static CanSignal VehicleOverspeed{ 14, 2, gSignalName_VehicleOverspeed, 1, 0, canIntel, canUint, 3, 0, 0};
static CanSignal *TCO1_arraySignals[TCO1_NumberOfSignals] = {&DirectionIndicator, &Driver1TimeRelatedStates, &Driver1WorkingState, &Driver2TimeRelatedStates, &Driver2WorkingState, &DriverCard_Driver1, &DriverCard_Driver2, &HandlingInformation, &SystemEvent, &TachographOutputShaftSpeed, &TachographPerformance, &TachographVehicleSpeed, &VehicleMotion, &VehicleOverspeed};
const messageNameCharStruct gMessageName_TCO1{"TCO1",MAX_LENGTH_NAME};
static CanMessageRx TCO1(gMessageName_TCO1, TCO1_arraySignals, TCO1_NumberOfSignals, 0x0CFE6C18, 8, 50);

const uint8_t TCO1_EE_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_TcoVehicleSpeed{"TcoVehicleSpeed",MAX_LENGTH_NAME};
static CanSignal TcoVehicleSpeed{ 48, 16, gSignalName_TcoVehicleSpeed, 390625, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *TCO1_EE_arraySignals[TCO1_EE_NumberOfSignals] = {&TcoVehicleSpeed};
const messageNameCharStruct gMessageName_TCO1_EE{"TCO1_EE",MAX_LENGTH_NAME};
static CanMessageRx TCO1_EE(gMessageName_TCO1_EE, TCO1_EE_arraySignals, TCO1_EE_NumberOfSignals, 0x18FE6CEE, 8, 50);

const uint8_t TIRE_NumberOfSignals = 4;
const signalNameCharStruct gSignalName_TireAxis{"TireAxis",MAX_LENGTH_NAME};
static CanSignal TireAxis{ 4, 4, gSignalName_TireAxis, 1, 0, canIntel, canUint, 15, 0, 0};
const signalNameCharStruct gSignalName_TireLocation{"TireLocation",MAX_LENGTH_NAME};
static CanSignal TireLocation{ 0, 4, gSignalName_TireLocation, 1, 0, canIntel, canUint, 15, 0, 0};
const signalNameCharStruct gSignalName_TirePressure{"TirePressure",MAX_LENGTH_NAME};
static CanSignal TirePressure{ 40, 8, gSignalName_TirePressure, 5.5, -101.3, canIntel, canUint, 1400, 100, 0};
const signalNameCharStruct gSignalName_TireTemp{"TireTemp",MAX_LENGTH_NAME};
static CanSignal TireTemp{ 48, 8, gSignalName_TireTemp, 1, -50, canIntel, canUint, 250, -50, 0};
static CanSignal *TIRE_arraySignals[TIRE_NumberOfSignals] = {&TireAxis, &TireLocation, &TirePressure, &TireTemp};
const messageNameCharStruct gMessageName_TIRE{"TIRE",MAX_LENGTH_NAME};
static CanMessageRx TIRE(gMessageName_TIRE, TIRE_arraySignals, TIRE_NumberOfSignals, 0x18FEF433, 8, 10000);

const uint8_t TTS6_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_Energy_for_traction_daily{"Energy_for_traction_daily",MAX_LENGTH_NAME};
static CanSignal Energy_for_traction_daily{ 32, 32, gSignalName_Energy_for_traction_daily, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Energy_for_traction_total{"Energy_for_traction_total",MAX_LENGTH_NAME};
static CanSignal Energy_for_traction_total{ 0, 32, gSignalName_Energy_for_traction_total, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *TTS6_arraySignals[TTS6_NumberOfSignals] = {&Energy_for_traction_daily, &Energy_for_traction_total};
const messageNameCharStruct gMessageName_TTS6{"TTS6",MAX_LENGTH_NAME};
static CanMessageRx TTS6(gMessageName_TTS6, TTS6_arraySignals, TTS6_NumberOfSignals, 0x18FF0CFD, 8, 0);

const uint8_t TTS7_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_Energy_with_recuperation_daily{"Energy_with_recuperation_daily",MAX_LENGTH_NAME};
static CanSignal Energy_with_recuperation_daily{ 32, 32, gSignalName_Energy_with_recuperation_daily, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Energy_with_recuperation_total{"Energy_with_recuperation_total",MAX_LENGTH_NAME};
static CanSignal Energy_with_recuperation_total{ 0, 32, gSignalName_Energy_with_recuperation_total, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *TTS7_arraySignals[TTS7_NumberOfSignals] = {&Energy_with_recuperation_daily, &Energy_with_recuperation_total};
const messageNameCharStruct gMessageName_TTS7{"TTS7",MAX_LENGTH_NAME};
static CanMessageRx TTS7(gMessageName_TTS7, TTS7_arraySignals, TTS7_NumberOfSignals, 0x18FF0DFD, 8, 0);

const uint8_t TTS8_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_Energy_recuperation_total{"Energy_recuperation_total",MAX_LENGTH_NAME};
static CanSignal Energy_recuperation_total{ 0, 32, gSignalName_Energy_recuperation_total, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Ratio_recup_to_energy_total{"Ratio_recup_to_energy_total",MAX_LENGTH_NAME};
static CanSignal Ratio_recup_to_energy_total{ 32, 32, gSignalName_Ratio_recup_to_energy_total, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *TTS8_arraySignals[TTS8_NumberOfSignals] = {&Energy_recuperation_total, &Ratio_recup_to_energy_total};
const messageNameCharStruct gMessageName_TTS8{"TTS8",MAX_LENGTH_NAME};
static CanMessageRx TTS8(gMessageName_TTS8, TTS8_arraySignals, TTS8_NumberOfSignals, 0x18FF0EFD, 8, 0);

const uint8_t TTS9_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_Energy_recuperation_daily{"Energy_recuperation_daily",MAX_LENGTH_NAME};
static CanSignal Energy_recuperation_daily{ 0, 32, gSignalName_Energy_recuperation_daily, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_Ratio_recup_to_energy_daily{"Ratio_recup_to_energy_daily",MAX_LENGTH_NAME};
static CanSignal Ratio_recup_to_energy_daily{ 32, 32, gSignalName_Ratio_recup_to_energy_daily, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *TTS9_arraySignals[TTS9_NumberOfSignals] = {&Energy_recuperation_daily, &Ratio_recup_to_energy_daily};
const messageNameCharStruct gMessageName_TTS9{"TTS9",MAX_LENGTH_NAME};
static CanMessageRx TTS9(gMessageName_TTS9, TTS9_arraySignals, TTS9_NumberOfSignals, 0x18FF0FFD, 8, 0);

const uint8_t VDC1_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_VDC_FullyOperational{"VDC_FullyOperational",MAX_LENGTH_NAME};
static CanSignal VDC_FullyOperational{ 2, 2, gSignalName_VDC_FullyOperational, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_VDC_InformationSignal{"VDC_InformationSignal",MAX_LENGTH_NAME};
static CanSignal VDC_InformationSignal{ 0, 2, gSignalName_VDC_InformationSignal, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *VDC1_arraySignals[VDC1_NumberOfSignals] = {&VDC_FullyOperational, &VDC_InformationSignal};
const messageNameCharStruct gMessageName_VDC1{"VDC1",MAX_LENGTH_NAME};
static CanMessageRx VDC1(gMessageName_VDC1, VDC1_arraySignals, VDC1_NumberOfSignals, 0x18FE4F0B, 8, 100);

const uint8_t VEP1_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_ActualVoltage_24v{"ActualVoltage_24v",MAX_LENGTH_NAME};
static CanSignal ActualVoltage_24v{ 32, 16, gSignalName_ActualVoltage_24v, 0.05, 0, canIntel, canUint, 3212.75, 0, 0};
static CanSignal *VEP1_arraySignals[VEP1_NumberOfSignals] = {&ActualVoltage_24v};
const messageNameCharStruct gMessageName_VEP1{"VEP1",MAX_LENGTH_NAME};
static CanMessageRx VEP1(gMessageName_VEP1, VEP1_arraySignals, VEP1_NumberOfSignals, 0x18FEF71E, 8, 1000);

const uint8_t ASC2_Tx_NumberOfSignals = 3;
const signalNameCharStruct gSignalName_KneelingControlModeReq{"KneelingControlModeReq",MAX_LENGTH_NAME};
static CanSignal KneelingControlModeReq{ 6, 2, gSignalName_KneelingControlModeReq, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_ReqRegulationBusFrontAxle{"ReqRegulationBusFrontAxle",MAX_LENGTH_NAME};
static CanSignal ReqRegulationBusFrontAxle{ 8, 4, gSignalName_ReqRegulationBusFrontAxle, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_ReqRegulationBusRearAxle{"ReqRegulationBusRearAxle",MAX_LENGTH_NAME};
static CanSignal ReqRegulationBusRearAxle{ 12, 4, gSignalName_ReqRegulationBusRearAxle, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ASC2_Tx_arraySignals[ASC2_Tx_NumberOfSignals] = {&KneelingControlModeReq, &ReqRegulationBusFrontAxle, &ReqRegulationBusRearAxle};
const messageNameCharStruct gMessageName_ASC2_Tx{"ASC2_Tx",MAX_LENGTH_NAME};
static CanMessageTx ASC2_Tx(gMessageName_ASC2_Tx, ASC2_Tx_arraySignals, ASC2_Tx_NumberOfSignals, 0x0CD22F17, 8, 100);

const uint8_t DB_1_NumberOfSignals = 13;
const signalNameCharStruct gSignalName_BtnBackAns{"BtnBackAns",MAX_LENGTH_NAME};
static CanSignal BtnBackAns{ 50, 2, gSignalName_BtnBackAns, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_BtnMinusAns{"BtnMinusAns",MAX_LENGTH_NAME};
static CanSignal BtnMinusAns{ 52, 2, gSignalName_BtnMinusAns, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_BtnOkAns{"BtnOkAns",MAX_LENGTH_NAME};
static CanSignal BtnOkAns{ 48, 2, gSignalName_BtnOkAns, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_BtnPlusAns{"BtnPlusAns",MAX_LENGTH_NAME};
static CanSignal BtnPlusAns{ 54, 2, gSignalName_BtnPlusAns, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_HearthBeat{"HearthBeat",MAX_LENGTH_NAME};
static CanSignal HearthBeat{ 0, 2, gSignalName_HearthBeat, 1, 0, canIntel, canUint, 3, 0, 0};
const signalNameCharStruct gSignalName_IpAddressByte_1{"IpAddressByte_1",MAX_LENGTH_NAME};
static CanSignal IpAddressByte_1{ 8, 8, gSignalName_IpAddressByte_1, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_IpAddressByte_2{"IpAddressByte_2",MAX_LENGTH_NAME};
static CanSignal IpAddressByte_2{ 16, 8, gSignalName_IpAddressByte_2, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_IpAddressByte_3{"IpAddressByte_3",MAX_LENGTH_NAME};
static CanSignal IpAddressByte_3{ 24, 8, gSignalName_IpAddressByte_3, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_IpAddressByte_4{"IpAddressByte_4",MAX_LENGTH_NAME};
static CanSignal IpAddressByte_4{ 32, 8, gSignalName_IpAddressByte_4, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_KL_15{"KL_15",MAX_LENGTH_NAME};
static CanSignal KL_15{ 46, 2, gSignalName_KL_15, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_ProgramBuild{"ProgramBuild",MAX_LENGTH_NAME};
static CanSignal ProgramBuild{ 56, 8, gSignalName_ProgramBuild, 1, 0, canIntel, canUint, 250, 0, 0};
const signalNameCharStruct gSignalName_ProgramSubVersion{"ProgramSubVersion",MAX_LENGTH_NAME};
static CanSignal ProgramSubVersion{ 40, 6, gSignalName_ProgramSubVersion, 1, 0, canIntel, canUint, 63, 0, 0};
const signalNameCharStruct gSignalName_ProgramVersion{"ProgramVersion",MAX_LENGTH_NAME};
static CanSignal ProgramVersion{ 2, 6, gSignalName_ProgramVersion, 1, 0, canIntel, canUint, 63, 0, 0};
static CanSignal *DB_1_arraySignals[DB_1_NumberOfSignals] = {&BtnBackAns, &BtnMinusAns, &BtnOkAns, &BtnPlusAns, &HearthBeat, &IpAddressByte_1, &IpAddressByte_2, &IpAddressByte_3, &IpAddressByte_4, &KL_15, &ProgramBuild, &ProgramSubVersion, &ProgramVersion};
const messageNameCharStruct gMessageName_DB_1{"DB_1",MAX_LENGTH_NAME};
static CanMessageTx DB_1(gMessageName_DB_1, DB_1_arraySignals, DB_1_NumberOfSignals, 0x18FF1017, 8, 1000);

const uint8_t DB_2_NumberOfSignals = 5;
const signalNameCharStruct gSignalName_AutoClossingDoors{"AutoClossingDoors",MAX_LENGTH_NAME};
static CanSignal AutoClossingDoors{ 4, 2, gSignalName_AutoClossingDoors, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_CpuLoad{"CpuLoad",MAX_LENGTH_NAME};
static CanSignal CpuLoad{ 48, 8, gSignalName_CpuLoad, 0.4, 0, canIntel, canUint, 100, 0, 0};
const signalNameCharStruct gSignalName_DisableSafety{"DisableSafety",MAX_LENGTH_NAME};
static CanSignal DisableSafety{ 2, 2, gSignalName_DisableSafety, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_MemLoad{"MemLoad",MAX_LENGTH_NAME};
static CanSignal MemLoad{ 56, 8, gSignalName_MemLoad, 0.4, 0, canIntel, canUint, 100, 0, 0};
const signalNameCharStruct gSignalName_PassengerDoorControl{"PassengerDoorControl",MAX_LENGTH_NAME};
static CanSignal PassengerDoorControl{ 0, 2, gSignalName_PassengerDoorControl, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DB_2_arraySignals[DB_2_NumberOfSignals] = {&AutoClossingDoors, &CpuLoad, &DisableSafety, &MemLoad, &PassengerDoorControl};
const messageNameCharStruct gMessageName_DB_2{"DB_2",MAX_LENGTH_NAME};
static CanMessageTx DB_2(gMessageName_DB_2, DB_2_arraySignals, DB_2_NumberOfSignals, 0x18FFA017, 8, 100);

const uint8_t DB_3_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_TurnLeftLamp{"TurnLeftLamp",MAX_LENGTH_NAME};
static CanSignal TurnLeftLamp{ 2, 2, gSignalName_TurnLeftLamp, 1, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_TurnRightLamp{"TurnRightLamp",MAX_LENGTH_NAME};
static CanSignal TurnRightLamp{ 0, 2, gSignalName_TurnRightLamp, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *DB_3_arraySignals[DB_3_NumberOfSignals] = {&TurnLeftLamp, &TurnRightLamp};
const messageNameCharStruct gMessageName_DB_3{"DB_3",MAX_LENGTH_NAME};
static CanMessageTx DB_3(gMessageName_DB_3, DB_3_arraySignals, DB_3_NumberOfSignals, 0x18FF1117, 8, 0);

const uint8_t ISOTP_DASHBOARD_ID_NumberOfSignals = 1;
const signalNameCharStruct gSignalName_IsoTpDataDB{"IsoTpDataDB",MAX_LENGTH_NAME};
static CanSignal IsoTpDataDB{ 0, 64, gSignalName_IsoTpDataDB, 1, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *ISOTP_DASHBOARD_ID_arraySignals[ISOTP_DASHBOARD_ID_NumberOfSignals] = {&IsoTpDataDB};
const messageNameCharStruct gMessageName_ISOTP_DASHBOARD_ID{"ISOTP_DASHBOARD_ID",MAX_LENGTH_NAME};
static CanMessageTx ISOTP_DASHBOARD_ID(gMessageName_ISOTP_DASHBOARD_ID, ISOTP_DASHBOARD_ID_arraySignals, ISOTP_DASHBOARD_ID_NumberOfSignals, 0x00FF0517, 8, 0);

const uint8_t VDHR_NumberOfSignals = 2;
const signalNameCharStruct gSignalName_TotalVehicleDistance{"TotalVehicleDistance",MAX_LENGTH_NAME};
static CanSignal TotalVehicleDistance{ 0, 32, gSignalName_TotalVehicleDistance, 0.005, 0, canIntel, canUint, 0, 0, 0};
const signalNameCharStruct gSignalName_TripDistance{"TripDistance",MAX_LENGTH_NAME};
static CanSignal TripDistance{ 32, 32, gSignalName_TripDistance, 0.005, 0, canIntel, canUint, 0, 0, 0};
static CanSignal *VDHR_arraySignals[VDHR_NumberOfSignals] = {&TotalVehicleDistance, &TripDistance};
const messageNameCharStruct gMessageName_VDHR{"VDHR",MAX_LENGTH_NAME};
static CanMessageTx VDHR(gMessageName_VDHR, VDHR_arraySignals, VDHR_NumberOfSignals, 0x18FEC117, 8, 1000);

const uint8_t numberOfRxMessages = 62;
static CanMessageRx *arrayRxMessages[numberOfRxMessages] = { &ADAS_1, &AIR1, &AMB, &ASC1, &ASC2_Rx, &AUXIO_R, &BCH1, &BDS, &BJM1, &CCU1_DB, &CCUT1, &CCVS1, &CCVS1_03, &CDC, &CL, &CM1, &CM1_E1, &DC1, &DC2, &DD1_12, &DD1_1E, &DLCC1, &DLCC2, &DLDC1, &DM1_EBS, &DM1_EPB, &DM1_Suspension, &DOZC_1, &DOZC_2, &EBC1, &EBC4, &EBC5, &ECO, &EDSC2_2, &EPBS1, &ESC2, &ET1, &ETC2, &FS1, &HVESSD1, &HVESSD2, &HVESSD3, &HVESSD5, &HVESSD6, &HVESSS1, &ISOTP_PC_ID, &LD, &LD_2, &MCU2VCU2, &OWW, &PCM1, &SCU2CLM, &T2B_TMS1, &TCO1, &TCO1_EE, &TIRE, &TTS6, &TTS7, &TTS8, &TTS9, &VDC1, &VEP1};
const uint8_t numberOfTxMessages = 6;
static CanMessageTx *arrayTxMessages[numberOfTxMessages] = { &ASC2_Tx, &DB_1, &DB_2, &DB_3, &ISOTP_DASHBOARD_ID, &VDHR};
CanDataBase gCanDB(arrayRxMessages,numberOfRxMessages,arrayTxMessages,numberOfTxMessages);
